package oracle.fodemo.storefront.store.service.common.serviceinterface;

import java.math.BigInteger;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.fodemo.storefront.store.queries.common.CustomerInfoVOSDO;
import oracle.fodemo.storefront.store.queries.common.OrderInfoVOSDO;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.common.service.types.ProcessData;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 12 16:30:14 MDT 2008
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="www.globalcompany.example.com", name="StoreFrontService",
    wsdlLocation="oracle/fodemo/storefront/store/service/common/serviceinterface/StoreFrontService.wsdl")
@SDODatabinding(schemaLocation="oracle/fodemo/storefront/store/service/common/serviceinterface/StoreFrontService.xsd")
public interface StoreFrontService {


    public static final String NAME = "{www.globalcompany.example.com}StoreFrontService";

    /**
     * @param orderInfoVO1
     * @throws ServiceException
     */
    @WebMethod(action="www.globalcompany.example.com/deleteOrderInfoVOSDO",
        operationName="deleteOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="deleteOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="deleteOrderInfoVOSDOResponse")
    void deleteOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN, name="orderInfoVO1")
        OrderInfoVOSDO orderInfoVO1) throws ServiceException;


    @WebMethod(action="www.globalcompany.example.com/findCustomerInfoVO1",
        operationName="findCustomerInfoVO1")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="findCustomerInfoVO1")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="findCustomerInfoVO1Response")
    @WebResult(name="result")
    List<CustomerInfoVOSDO> findCustomerInfoVO1(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/findCustomerInfoVO1CustomerInfoVOCriteria",
        operationName="findCustomerInfoVO1CustomerInfoVOCriteria")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="findCustomerInfoVO1CustomerInfoVOCriteria")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="findCustomerInfoVO1CustomerInfoVOCriteriaResponse")
    @WebResult(name="result")
    List<CustomerInfoVOSDO> findCustomerInfoVO1CustomerInfoVOCriteria(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="CustId")
        String CustId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/getOrderInfoVOSDO",
        operationName="getOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="getOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="getOrderInfoVOSDOResponse")
    @WebResult(name="result")
    OrderInfoVOSDO getOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN, name="orderId")
        BigInteger orderId) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/createOrderInfoVOSDO",
        operationName="createOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="createOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="createOrderInfoVOSDOResponse")
    @WebResult(name="result")
    OrderInfoVOSDO createOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN,
            name="orderInfoVO1")
        OrderInfoVOSDO orderInfoVO1) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/updateOrderInfoVOSDO",
        operationName="updateOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="updateOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="updateOrderInfoVOSDOResponse")
    @WebResult(name="result")
    OrderInfoVOSDO updateOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN,
            name="orderInfoVO1")
        OrderInfoVOSDO orderInfoVO1) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/mergeOrderInfoVOSDO",
        operationName="mergeOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="mergeOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="mergeOrderInfoVOSDOResponse")
    @WebResult(name="result")
    OrderInfoVOSDO mergeOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN,
            name="orderInfoVO1")
        OrderInfoVOSDO orderInfoVO1) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/findOrderInfoVOSDO",
        operationName="findOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="findOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="findOrderInfoVOSDOResponse")
    @WebResult(name="result")
    List<OrderInfoVOSDO> findOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/processOrderInfoVOSDO",
        operationName="processOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="processOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="processOrderInfoVOSDOResponse")
    @WebResult(name="result")
    List<OrderInfoVOSDO> processOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN,
            name="changeOperation")
        String changeOperation, @WebParam(mode = WebParam.Mode.IN, name="orderInfoVO1")
        List<OrderInfoVOSDO> orderInfoVO1, @WebParam(mode = WebParam.Mode.IN,
            name="processControl")
        ProcessControl processControl) throws ServiceException;

    @WebMethod(action="www.globalcompany.example.com/processCSOrderInfoVOSDO",
        operationName="processCSOrderInfoVOSDO")
    @RequestWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="processCSOrderInfoVOSDO")
    @ResponseWrapper(targetNamespace="www.globalcompany.example.com/types/",
        localName="processCSOrderInfoVOSDOResponse")
    @WebResult(name="result")
    ProcessData processCSOrderInfoVOSDO(@WebParam(mode = WebParam.Mode.IN,
            name="processData")
        ProcessData processData, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;
}
