package devguide.examples.readonlyvo.queries.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface PersonsRow extends Row {
    Number getPersonId();

    void setPersonId(Number value);

    String getEmail();

    void setEmail(String value);

    String getFirstName();

    void setFirstName(String value);

    String getLastName();

    void setLastName(String value);

    String getPersonTypeCode();

    void setPersonTypeCode(String value);

    Number getPrimaryAddressId();

    void setPrimaryAddressId(Number value);

    String getShortName();

    void setShortName(String value);
}
