package oracle.foddemo.masterpricelist.model.queries.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 11 16:31:17 PST 2008
// ---------------------------------------------------------------------
public interface ProductsVO extends ViewObject {
    void executeAdvancedProductQuery(String searchTerm, String categoryId,
                                     Boolean includeDiscontinued);

    void executeSimpleProductQuery(String searchTerm,
                                   Boolean includeDiscontinued);
}
