package devguide.advanced.postingorder.client;

import devguide.advanced.postingorder.Result;
import devguide.advanced.postingorder.common.PostModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PostModuleClient extends ApplicationModuleImpl implements PostModule {
    /**This is the default constructor (do not remove).
     */
    public PostModuleClient() {
    }

    public Result newProductForNewSupplier(String supplierName, 
                                           String supplierStatus, 
                                           String productName, 
                                           String productStatus, 
                                           Number listPrice, Number minPrice, 
                                           String shipCode) {
        Object _ret = 
            this.riInvokeExportedMethod(this,"newProductForNewSupplier",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","oracle.jbo.domain.Number","oracle.jbo.domain.Number","java.lang.String"},new Object[] {supplierName, supplierStatus, productName, productStatus, listPrice, minPrice, shipCode});
        return (Result)_ret;
    }
}
