package devguide.advanced.customprops.common;

import java.io.Serializable;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface Products extends ViewObject {
    void setViewObjectCustomProperty(String name, Serializable value);

    void setViewObjectAttrCustomProperty(String attrName, String propName, 
                                         Serializable value);
}
