package oracle.fodemo.storefront.store.queries.client;

import oracle.fodemo.storefront.store.queries.common.OrderItemsVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderItemsVOClient extends ViewUsageImpl implements OrderItemsVO {
    /**This is the default constructor (do not remove).
     */
    public OrderItemsVOClient() {
    }


    /**
     * @param newQuantity
     */
    public void setQuantityForCurrentRow(Integer newQuantity) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setQuantityForCurrentRow",new String [] {"java.lang.Integer"},new Object[] {newQuantity});
        return;
    }

//    public void deleteCurrentItem() {
//        Object _ret =
//            getApplicationModuleProxy().riInvokeExportedMethod(this,"deleteCurrentItem",null,null);
//        return;
//    }

    /**
     * @param orderId
     */
    public void showOrderItemsForOrderId(Long orderId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"showOrderItemsForOrderId",new String [] {"java.lang.Long"},new Object[] {orderId});
        return;
    }
}
