package oracle.fodemo.storefront.store.queries.client;

import oracle.fodemo.storefront.store.queries.common.PersonsVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 08 16:20:17 MST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonsVOClient extends ViewUsageImpl implements PersonsVO {
    /**
     * This is the default constructor (do not remove).
     */
    public PersonsVOClient() {
    }

    public String getuserPrincipal() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getuserPrincipal",null,null);
        return (String)_ret;
    }

    public String findPerson(String principalName) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"findPerson",new String [] {"java.lang.String"},new Object[] {principalName});
        return (String)_ret;
    }
}
