package devguide.advanced.baseproject.extsub;

import devguide.advanced.baseproject.extsub.common.Products;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductsImpl extends ViewObjectImpl implements Products {
    /**This is the default constructor (do not remove).
     */
    public ProductsImpl() {
    }
    public void someCustomMethodOnProducts(String arg) {
      System.out.println("## someCustomMethodOnProducts Called ##");
    }
}
