package oracle.fodemo.storefront.store.service.client;

import java.util.List;


import oracle.fodemo.storefront.store.service.common.StoreServiceAM;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StoreServiceAMClient extends ApplicationModuleImpl implements StoreServiceAM {
    /**This is the default constructor (do not remove).
     */
    public StoreServiceAMClient() {
    }


    public void deleteCurrentMyOrderItem() {
        Object _ret =
            this.riInvokeExportedMethod(this,"deleteCurrentMyOrderItem",null,null);
        return;
    }

    public void executeMyOrdersForCustomerVO() {
        Object _ret =
            this.riInvokeExportedMethod(this,"executeMyOrdersForCustomerVO",null,null);
        return;
    }

    public void userRegistrationCreate(String userType) {
        Object _ret =
            this.riInvokeExportedMethod(this,"userRegistrationCreate",new String [] {"java.lang.String"},new Object[] {userType});
        return;
    }

    public void updateUserInterests(List pCategoryIds) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateUserInterests",new String [] {"java.util.List"},new Object[] {pCategoryIds});
        return;
    }

    public void userRegistrationCreateAddress() {
        Object _ret =
            this.riInvokeExportedMethod(this,"userRegistrationCreateAddress",null,null);
        return;
    }

    public Row setAuthenticatedUser() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setAuthenticatedUser",null,null);
        return (Row)_ret;
    }

    public void reconcileShoppingCart() {
        Object _ret =
            this.riInvokeExportedMethod(this,"reconcileShoppingCart",null,null);
        return;
    }

    public void removeAllItemsFromCart() {
        Object _ret =
            this.riInvokeExportedMethod(this,"removeAllItemsFromCart",null,null);
        return;
    }

    public void removeItemFromCart(Integer productId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"removeItemFromCart",new String [] {"java.lang.Integer"},new Object[] {productId});
        return;
    }

    public void updateItemInCart(Integer productId, Integer quantity,
                                 Boolean isSet) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateItemInCart",new String [] {"java.lang.Integer","java.lang.Integer","java.lang.Boolean"},new Object[] {productId, quantity, isSet});
        return;
    }

    public void resetProductQueryCriteria() {
        Object _ret =
            this.riInvokeExportedMethod(this,"resetProductQueryCriteria",null,null);
        return;
    }

    public void updateCustomerInterests(List pCategoryIds) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateCustomerInterests",new String [] {"java.util.List"},new Object[] {pCategoryIds});
        return;
    }

    public void userRegistrationPOCreate() {
        Object _ret =
            this.riInvokeExportedMethod(this,"userRegistrationPOCreate",null,null);
        return;
    }
}
