package oracle.fodemo.storefront.account.queries.client;


import oracle.fodemo.storefront.account.queries.common.CustomerAddressVO;

import oracle.jbo.Key;
import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerAddressVOClient extends ViewUsageImpl implements CustomerAddressVO {
    /**This is the default constructor (do not remove).
     */
    public CustomerAddressVOClient() {
    }


    public void refreshRemoveNewCurrentRow() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"refreshRemoveNewCurrentRow",null,null);
        return;
    }

    /**
     * @param pRowKey
     */
    public void refreshRemoveNewRowByKey(Key pRowKey) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"refreshRemoveNewRowByKey",new String [] {"oracle.jbo.Key"},new Object[] {pRowKey});
        return;
    }

    public void refreshAndDiscardChanges() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"refreshAndDiscardChanges",null,null);
        return;
    }
}
