REM $Id: PRODUCT_TRANSLATIONS.sql 2287 2007-09-06 23:43:36Z drmills $

-- INSERTING into PRODUCT_TRANSLATIONS
Insert into PRODUCT_TRANSLATIONS values (1,'EN','EN',
    'The TH-42PX60U 42-inch Diagonal Plasma HDTV gives you deep blacks, bright whites and 29 billion colors -- it''s an image so close to real life, you''ll swear you were in your favorite programs instead of just watching them. Enjoy crisp, lifelike details with the up to 10,0001 contrast ratio. 
    Deep blacks provide excellent shadow detail during dark scenes, while brilliant whites render bright scenes with vivid realism. Receive and view local over-the-air broadcasts in stunning HDT, using the built-in HDTV tuner. You can even share your JPEG photos taken with the built-in SD card slot. 
    Features a width-to-height ratio similar to movie theater screens, providing a theater-like experience at home. View HDTV broadcasts and widescreen DVDs the way they were meant to be seen. Native Resolution - 1366 x 768 Contrast Ratio - Up to 10,000 - 1 Progressive Scan Video Noise Reduction Digital Comb Filter Color Purity Optimizer (3D Color Management) 
    Two 20-watt, 8 ohm speakers -- 70Hz - 17kHz, 10% THD Surround Sound Motion Pattern Noise Reduction BBE ViVA HD3D Sound Standard NTSC tuner ATSC/QAM (SDTV and HDTV broadcasts) SD Card Slot and Photo Viewer HDMI-HDCP Interface - 2, in rear Analog Audio Input (for HDMI) - 1 rear Composite Video Input - 3 (2 rear, 1 front) S-Video Inputs - 3 (2 rear, 1 front) 
    Audio Input (for Video) - 3 (2 rear, 1 front) Rear Inputs/Outputs - 2 Component Video (YPbPr), 2 Component Audio out, 1 Composite and Audio out On-screen display languages - English/Spanish/French Timers - Sleep/On/Off Built-in closed-caption decoder Video Input Labeling V-Chip Program Lockout Includes remote control and pedestal stand Unit Dimensions(HxWxD) - 27.8 x 40.2 x 3.7 Unit Weight - 65 lbs',
    'HDMI (High-Definition Multimedia Interface) is a lossless, uncompressed, all-digital audio/video interface to link any AV source with an audio and/or video monitor, such as a digital television (DTV). HDMI supports standard-definition (SD), enhanced definition (ED), or high-definition (HD) video, plus multi-channel digital audio--all using a single cable. 
    If a component doesn''t have an HDMI connection, you''ll also get great picture reproduction using the three-jack component video (Y/Pb/Pr) input, which provides separate connections for luminance (Y), blue color difference (PB) and red color difference (PR). This results in increased bandwidth for color information, resulting in a more accurate picture with clearer color reproduction and less bleeding than you would get with S-Video or composite (RCA yellow video plug) connections. 
    Component video output is available only for DVD playback.',
    0,sysdate,0,sysdate,0);
Insert into PRODUCT_TRANSLATIONS values (2,'EN','EN',
    'Whether you''re a die-hard PlayStation 2 fan or a new player, this totally redesigned PlayStation 2 console will meet the demands of your game playing. The internal design architecture has been completely overhauled. Internal volume has been reduced by 75 percent, the system''s overall weight and thickness has been reduced incredibly. 
    The smaller, sleeker design makes it easy to carry around and enjoy games any time, anywhere. It keeps the PS2''s powerful 300MHz processor, for enhanced clarity and mesmerizing graphics. Also comes with one standard PS2 controller.',
    'MODEL- 97064 VENDOR- SONY PLAYSTATION FEATURES- PlayStation 2 Compact System- Charcoal Black Smaller, Slimmer and Network Ready PlayStation 2! While inheriting the basic functions and design philosophy of the current PlayStation 2 (SCPH-50000), 
    the internal design architecture of the new redesigned PlayStation 2 computer entertainment system (SCPH-70000 CB) model has been completely overhauled, resulting in a slimmer and more lightweight form. 
    Internal volume has been reduced by 75 percent, overall weight has been halved, and thickness trimmed down to 2.8 cm (thickness of current model is 7.8cm). Its size is almost as small as a hardcover book, making it easier to carry around. 
    Equipped with an integrated Ethernet port for network gaming, the PlayStation 2 sets new standards in the fusion of design and functionality. Approximately 40 percent of North American PlayStation 2 online gamers use dial-up connections and to satisfy this base, the North American model is equipped with both Ethernet and modem ports. 
    Includes PlayStation 2 console, Analog Controller (DUALSHOCK 2), AV Cable (integrated audio/video), AC Adaptor (AC power cord included). -- SPECIFICATIONs -- CPU - CPU : 128-bit CPU System Clock Frequency : 294.912 MHz Cache Memory : Instruction: 16KB, Data: 8KB + 16 K (ScrP) Main Memory : Direct Rambus (Direct RDRAM) Memory Size : 32MB Memory Bus Bandw',
    0,sysdate,0,sysdate,0);
Insert into PRODUCT_TRANSLATIONS values (3,'EN','EN',
    'The unlocked PalmOne Treo 650 boasts all the legendary features of the venerable Treo 600, plus a whole lot more. Now with Bluetooth, a higher resolution screen, a removable battery, and an improved keyboard, the Treo 650 is once again on the cutting edge of Smartphone technology. 
    It offers all the functionality of a high-end Palm OS-powered PDA, a cell phone and a VGA camera. Simply put, it''s the ultimate mobile office companion.',
    'Get All You Need, All In One Treo 650 PDA Unlocked GSM Phone The Treo™ 650 smartphone from palmOne makes it easier than ever to stay connected. It simplifies your life by combining a compact mobile phone with email, an organizer, messaging, and web access. 
    There’s also Bluetooth® technology so you can connect wirelessly to other Bluetooth devices. Not to mention an MP3 player, a digital camera that captures video, and a vibrant color screen that brings everything to life – all in a device that’s still small enough to fit in your pocket. Seems like Treo smartphones just keep getting smarter. 
    The Treo 650 smartphone looks and feels just like a phone, but it’s so much more. Carry thousands of business and personal phone numbers with you, and dial any of them by name from your contacts list. Or enter a name or number on the QWERTY keyboard. 
    There’s even an on-screen dial pad. Speakerphone, speed dial, conference calling, call history, and caller ID make managing all your calls that much easier. 
    Available as a dual-band digital CDMA phone, and as a GSM quad-band world phone. The included VersaMail® email client makes it easy to access and manage your email on the go – whether you use a popular desktop email client, IMAP or POP3. View photos, HTML, and even native Microsoft Word, Excel, and PowerPoint attachments. 
    Synchronize your corporate Microsoft Exchange email and calendar with built-in Microsoft Exchange ActiveSync®',
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (4,'EN','EN','The Palm® Treo™ 700w smartphone delivers everything you need without compromise. It combines a smarter phone with broadband-like speeds2 and rich-media capabilities, all in one—bringing Palm''s world-class ease of use to the Windows Mobile® platform. Connect with people in multiple ways—by voice, email, SMS, or MMS3. Your contacts are always reachable, from any application. Access email, the web, and corporate networks on one of the fastest networks available in the U.S.2, 3 Or relax and play your favorite music and videos right on your device. With this easy-to-use productivity device in hand, you can stay connected3 on your terms.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (5,'EN','EN','The sleek and powerful Palm Tungsten E handheld comes packed for business and priced for value.Access your calendar, contacts and important information anywhere. Create and edit Word, Excel and PowerPoint-compatible files on the run. Synchronize with Outlook''s calendar, contacts, tasks, notes and email right out of the box. Stay productive using updated features to Palm''s award winning organization software. Listen to MP3s, watch video clips and view photos wherever you go.A powerful ARM processor lets you listen to MP3s while looking up an address or scheduling an appointment. Watch the latest movie trailer or a new sales video. Carry digital photo albums of friends and family, students and co-workers, even the latest real estate listings. Plus it''s expandable, and with 32MB of memory there''s plenty of room to customize from more than 18,000 applications (sold separately).',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (6,'EN','EN','This is the original XBOX Microsoft video game system, delivering the most powerful games experiences ever. Xbox empowers game artists by giving them the technology to fulfill their creative visions as never before, creating games that blur the lines between fantasy and reality. The Xbox video game system and controller are designed to capture the power and performance that Xbox will deliver and are based on the input of more than 5,000 gamers and games creators from around the world. Sleek and powerful in its look, in a rich shade of black, the Xbox video game system is emblazoned with a large "X" and a signature green Xbox "jewel" positioned in its center. Four game controller ports that allow easy multiplayer gaming and enable other peripherals, ranging from game pads to voice-activated headsets. A front-loading DVD tray. A multisignal audio-video connector that allows for easy hookup to televisions and home theater systems. 
    An Ethernet port for rich, fast-action online gaming via a broadband connection. An NVIDIA graphics processing unit (GPU), delivering superior graphic performance. An Intel 733MHz processor, the most powerful CPU of any console. An internal hard drive, for massive storage of game information - a first in the console gaming industry.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (7,'EN','EN','Xbox 360 sets a new pace for digital entertainment. More than just a cutting-edge game system, Xbox 360 also integrates high-definition video, DVD movie playback, digital music, photos, and online connectivity into one sleek, small tower.',
    'Includes: Xbox 360 Console, 1 Wireless Xbox 360 Controller, Hard Drive, Headset, Standard A/V Cable, Faceplate, and Silver Xbox Live.The Xbox 360 System is the way to begin experiencing the ultimate in next-generation gaming. Amazing Digital entertainment experiences, unprecedented in home console entertainment, are waiting for you -- all you have to do is connect the controller to this incredible device and an unsurpassed level of adventure and excitement is yours. 
    Connect up to 4 wireless game controllers Online optimization - The XBox 360 is Wi-Fi ready (802.11a, b and g), has a built-in Ethernet port and has out-of-the-box access to Xbox Live Full digital media support - Plays DVD-Video, DVD-ROM, DVD-R/RW, DVD+R/RW, CD-DA, CD-ROM, CD-R, CD-RW, WMA CD, MP3 CD, JPEG Photo CD Streams media from portable MP3 players or a Windows XP based PC 3 USB 2.0 ports, two memory unit slots Multi-channel Surround sound,
    Supports 48KHz 16-Bit Audio Stands vertically or horizontally Interchangeable face plates personalize your XBox 360 console Dimensions(HxWxD) - 3.27 x 12.17 x 10.16 (83 x 309 x 258 mm) Weight - 7.7 lbs (3.49 Kg)',
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (8,
    'EN','EN','The era of no-compromises handheld gaming has arrived. Get ready for immersive, 3D gaming on a console that is poised to change the way we think about portable devices. 
    With wireless internet, video and digital music playback, and incredible data storage and connectivity options, the Sony PSP--or PlayStation Portable--is a complete solution for the mobile digital lifestyle. Sony has hit the mark by combining both horsepower and groundbreaking features into a package that weighs just a hair more than half a pound.',
    'The awe and excitement that has made Sony Playstation so popular as a TV game now lets you take it on the road and do more than you magined. The PSP is more than a portable version of Playstation. It''s a portable entertainment center with MP3 and MP4 download and play capabilities. 
    This nearly pocketable portable has a built-in, bright, high-resolution 4.3 inch (diagonal) color TFT LCD widescreen (for 16:9 perspective), built-in stereo speakers, and amazing connectivity. With an integrated 802.11b WiFi processor, you can share your online games over wireless networks - where available. 
    In addition to playing exciting games exclusively designed for the PSP on its UMD drive, there are also a number of movies available. UMD is a small, high-capacity optical disc that allows up to 1.8 GB - providing an extremely versatile format for games, music, and video. A built-in USB 2.0 slot enables computer connectivity for downloading music as ATRAC and MP3 files, video as MP4 files, photos as JPEG and online connectivity. Files may also be stored on MemoryStick Duo digital-media cards. 
    Built-in stereo speakers Input / Output Connectivity - 1 audio out, 1 microphone in, 1 control connector, 1 x USB 2.0, 1 Memory Stick Pro Duo slot, IrDA wireless, IR remote (allows simultaneous multiple PSPs to be connected) / Integrated Communications - 802.11b Wi-Fi Sony Proprietary UMD Drive Power - PSP''s battery is a removable, rechargeable lithium-ion battery. It''s possible to charge the PSP while using the system Control Buttons - Square, Triangle, X, and Circle face buttons, a digital pad, start, select, an analog thumb stick and two shoulder buttons on the top / Brightness control and Sound mode selectors.
    Built-in copyright protection system utilizes a combination of a unique disc ID, a 128-bit AES encryption key for media, and individual ID for each PSP unit',
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (9,'EN','EN','Lighter, brighter and just as fun as the original Nintendo DS, the Nintendo DS Lite arrives just in time for hungry gamers. It''s smaller than the original DS, with brighter screens and adjustable backlighting. The DS Lite sets itself apart from every other hand-held gaming system on the market with a variety of new features. Center microphone Larger stylus for a better grip Easy-to-reach Start and Select buttons Removable cover keeps the Game Boy Advance cartridge slot clear from dust and debris when not in use Color - Polar White',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (14,'EN','EN','Streamlined and sophisticated, the Bluetooth Headset H500 provides wireless connectivity and convenience. Combining an ergonomic design and versatile ear hook, this sleek headset can be worn on either ear. Created to be ultra comfortable, the Motorola H500 is so easy to wear that you''ll forget you even have it on! But don''t be fooled by its good looks - this petite powerhouse provides impressive battery power to boot and an omni-directional microphone to clearly pick up your voice. A perfect companion for a variety of Bluetooth compatible 1.2- and 1.1-enabled mobile phones, the Motorola H500 is a must-have accessory for communicating in style. 
    The Motorola H500 works with you to help you communicate on the go - connecting with devices up to 30 feet away. Or give your mobile a rest and connect with your Bluetooth-enabled PC for hands-free Voice over IP VoIP use. Offering improved comfort and sound quality over its predecessor, the Motorola H500 provides a sleek, ergonomic design that fits to your ear, allowing for comfortable wear over extended periods and providing an enhanced seal for outstanding audio performance. Style and comfort are only part of this package - the headset boasts up to 8 hours of talk time or 130 hours of standby time from a single charge, giving you plenty of juice for all of your wireless connections! 
    Whether you are managing the office or party planning on-the-go, the Motorola H500 is perfect for multi-tasking with flair. Equipped with a multifunction button it''s easy to place, receive or end calls - all from one button! Advanced volume controls include orientation technology to assure that volume controls will always be upright Blue LED light to notify when the headset is in use, or turn off this feature if you choose Bluetooth 1.2 provides quicker pairing, better audio with less dropped calls and reduced interference from other devices Skype certified',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (15,'EN','EN','The Portable Audio System for iPod and iPod Photo allows you to play your iPod through a portable speaker system. Just put your iPod in the dock, then press play. It''s that easy. The revolutionary MaxxBass technology creates quality bass without a subwoofer, and the built-in docking station provides the same synchronization, data transfer, and recharging options as your iPod dock. The convenient secondary input jack provides for connection with other audio devices, including laptops, older iPods, and other MP3 players. The IM3C fits, syncs, and charges the iPod, iPod photo, iPod mini, and iPod nano players.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (16,'EN','EN','The Creative Zen Vision W Multimedia Player lets you take all your movies, music and photos in a light, pocket-sized device that is loaded with 30 or 60 GB of memory. At this capacity you can carry tens of thousands of photos, 240 hours of movies (500 Kbps MPEG4-SP), or up to 30,000 songs (WMA encoded at 64 Kbps), all in the palm of your hand. You can also tune in the radio (32 station presets), record your favorite talk show, or make personal voice memos with the built-in microphone. And the big news about the Vision W is that it displays your media in a widescreen, 16:9 format.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (17,'EN','EN',
    'Apple iPod - Continuing its tradition of hardware and software innovation and design, Apple has released a new iPod that surpasses the last. This update to the 5th generation iPod with video playback features a huge 80GB hard drive - the largest yet! With iTunes 7 ushering in movie and game downloads, there''s more than enough content to satisfy this beast of a media player. You also get a 2.5" display that is now 60% brighter, a higher capacity battery for up to 20 hrs. of music and 6.5 hrs. of video, and a set of newly designed iPod earbuds. Ports - dock connector, Stereo minijack, composite video and audio through minijack Connectivity - USB through dock connector, composite video (with A/V cable - sold separately), and audio through headphone jack or line out on the iPod Universal Dock (sold separately) 
    Charge Time - about 4 hrs. (2 hrs. fast charge to 80% capacity) Audio Support - AAC (16 to 320 Kbps), Protected AAC (from iTunes Music Store), MP3 (16 to 320 Kbps), MP3 VBR, Audible (formats 2, 3, and 4), Apple Lossless, WAV, and AIFF Photo Support - syncs iPod-viewable photos in JPEG, BMP, GIF, TIFF, PSD (Mac only), and PNG formats Video Support - H.264 video - up to 768 Kbps, 320 x 240, 30 fps, Baseline Profile up to Level 1.3 with AAC-LC up to 160 Kbps, 48 Khz, stereo audio in. m4v,. mp4 and. mov file formats / MPEG-4 video - up to 2.5 mbps, 480 x 480, 30 fps, Simple Profile with AAC-LC up to 160 Kbps, 48 Khz, stereo audio in. m4v,. mp4 and. mov file formats Backlight Timer Sleep Timer 20 Equalizer Settings Shuffle Songs or Albums Date and Time Unit Dimensions - 4.1 x 2.4 x 0.55 Unit Weight - 5.5 oz.',null,
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (18,'EN','EN',
    'The Apple 1 GB Shuffle is the world''s smallest digital music player that lets you wear up to 240 songs on your sleeve, or your lapel, or your belt--it''s so small you can wear it just about anywhere. Clip on iPod Shuffle and wear it as a badge of musical devotion. And with the shuffle''s anodized aluminum enclosure it is durable and goes with almost any outfit. About the size of a matchbook, the iPod Shuffle measures up nicely. Just clip it and go. It comes with a teeny little docking station. Although the Shuffle comes in a small package, 1.62 inches long and about half an ounce, it still holds a lot of music, and you can count on your Shuffle to keep on rocking for up to 12 continuous hours. 
    Use iTunes to import your CDs, shop for songs on the iTunes Store, and then sync them to your iPod Shuffle. 
    And if you have more than 240 songs in your iTunes library, let iTunes autofill your Shuffle and get a new musical experience every time.',null,
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (19,'EN','EN',
    'Apple iPod - Continuing its tradition of hardware and software innovation and design, Apple has released a new iPod that surpasses the last. This update to the 5th generation iPod with video playback features a huge 80GB hard drive - the largest yet! 
    With iTunes 7 ushering in movie and game downloads, there''s more than enough content to satisfy this beast of a media player. You also get a 2.5" display that is now 60% brighter, a higher capacity battery for up to 20 hrs. of music and 6.5 hrs. of video, and a set of newly designed iPod earbuds. Ports - dock connector, Stereo minijack, composite video and audio through minijack Connectivity - USB through dock connector, composite video (with A/V cable - sold separately), and audio through headphone jack or line out on the iPod Universal Dock (sold separately) 
    Charge Time - about 4 hrs. (2 hrs. fast charge to 80% capacity) Audio Support - AAC (16 to 320 Kbps), Protected AAC (from iTunes Music Store), MP3 (16 to 320 Kbps), MP3 VBR, Audible (formats 2, 3, and 4), Apple Lossless, WAV, and AIFF Photo Support - syncs iPod-viewable photos in JPEG, BMP, GIF, TIFF, PSD (Mac only), and PNG formats Video Support - H.264 video - up to 768 Kbps, 320 x 240, 30 fps, Baseline Profile up to Level 1.3 with AAC-LC up to 160 Kbps, 48 Khz, stereo audio in. m4v,. mp4 and. mov file formats / MPEG-4 video - up to 2.5 mbps, 480 x 480, 30 fps, Simple Profile with AAC-LC up to 160 Kbps, 48 Khz, stereo audio in. m4v,. mp4 and. mov file formats Backlight Timer Sleep Timer 20 Equalizer Settings Shuffle Songs or Albums Date and Time Unit Dimensions - 4.1 x 2.4 x 0.55 Unit Weight - 5.5 oz.',null,
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (20,'EN','EN','Apple iPod - Continuing its tradition of hardware and software innovation and design, Apple has released a new iPod that surpasses the last. This update to the 5th generation iPod with video playback features a huge 80GB hard drive - the largest yet! With iTunes 7 ushering in movie and game downloads, there''s more than enough content to satisfy this beast of a media player. You also get a 2.5" display that is now 60% brighter, a higher capacity battery for up to 20 hrs. of music and 6.5 hrs. of video, and a set of newly designed iPod earbuds. Ports - dock connector, Stereo minijack, composite video and audio through minijack Connectivity - USB through dock connector, composite video (with A/V cable - sold separately), and audio through headphone jack or line out on the iPod Universal Dock (sold separately) Charge Time - about 4 hrs. (2 hrs. fast charge to 80% capacity) Audio Support - AAC (16 to 320 Kbps), Protected AAC (from iTunes Music Store), MP3 (16 to 320 Kbps), MP3 VBR, Audible (formats 2, 3, and 4), Apple Lossless, WAV, and AIFF Photo Support - syncs iPod-viewable photos in JPEG, BMP, GIF, TIFF, PSD (Mac only), and PNG formats Video Support - H.264 video - up to 768 Kbps, 320 x 240, 30 fps, Baseline Profile up to Level 1.3 with AAC-LC up to 160 Kbps, 48 Khz, stereo audio in. m4v,. mp4 and. mov file formats / MPEG-4 video - up to 2.5 mbps, 480 x 480, 30 fps, Simple Profile with AAC-LC up to 160 Kbps, 48 Khz, stereo audio in. m4v,. mp4 and. mov file formats Backlight Timer Sleep Timer 20 Equalizer Settings Shuffle Songs or Albums Date and Time Unit Dimensions - 4.1 x 2.4 x 0.55 Unit Weight - 5.5 oz.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (21,'EN','EN','Includes: earbud headphones, USB 2.0 cable, dock adapter, case, iTunes for Windows and Mac, and more. Come one, come all and witness the incredible shrinking iPod! With the nano, Apple introduces the latest member of the highly successful iPod family of digital audio players. The nano is aptly named since it''s a fraction of the size of its larger iPod cousins. It is the width of a pencil and comes in at a feather-light 1.5 ounces. For Apple''s next trick, they''ve taken this new, diminutive iPod and added all of the features of a regular iPod. You get a bright, full-color display, Apple''s famous Click Wheel, and up to 14 hours of battery life. With that said, take a peek behind the curtain and be amazed at the rest of what the iPod nano has to offer: Connector for optional dock; stereo minijack; charge time: about 3 hours (1.5 hour fast charge to 80% capacity); AAC (16 to 320 Kbps); Protected AAC (from iTunes Music Store); MP3 (16 to 320 Kbps); MP3 VBR; Audible (formats 2, 3, and 4); Apple Lossless; WAV; AIFF; photo support: JPEG/BMP/GIF/TIFF/PSD (Mac only)/PNG; sync and charge via USB cable; adjust audiobook playback speed; create multiple on-the-go playlists; shuffle songs or albums; repeat one or all; 20 equalizer settings; backlight timer; display contrast; alarm; sleep timer; date and time; display time in menu bar; supports Windows 2000 with Service Pack 4 or later, Windows XP Home or Professional with Service Pack 2 or later, Mac OS X v10.3.4 or later; unit dimensions: 3.5 x 1.6 x 0.27; unit weight: 1.5 ounces. ',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (22,'EN','EN','Includes: earbud headphones, USB 2.0 cable, dock adapter, case, iTunes for Windows and Mac, and more. Come one, come all and witness the incredible shrinking iPod! With the nano, Apple introduces the latest member of the highly successful iPod family of digital audio players. The nano is aptly named since it''s a fraction of the size of its larger iPod cousins. It is the width of a pencil and comes in at a feather-light 1.5 ounces. For Apple''s next trick, they''ve taken this new, diminutive iPod and added all of the features of a regular iPod. You get a bright, full-color display, Apple''s famous Click Wheel, and up to 14 hours of battery life. With that said, take a peek behind the curtain and be amazed at the rest of what the iPod nano has to offer: Connector for optional dock; stereo minijack; charge time: about 3 hours (1.5 hour fast charge to 80% capacity); AAC (16 to 320 Kbps); Protected AAC (from iTunes Music Store); MP3 (16 to 320 Kbps); MP3 VBR; Audible (formats 2, 3, and 4); Apple Lossless; WAV; AIFF; photo support: JPEG/BMP/GIF/TIFF/PSD (Mac only)/PNG; sync and charge via USB cable; adjust audiobook playback speed; create multiple on-the-go playlists; shuffle songs or albums; repeat one or all; 20 equalizer settings; backlight timer; display contrast; alarm; sleep timer; date and time; display time in menu bar; supports Windows 2000 with Service Pack 4 or later, Windows XP Home or Professional with Service Pack 2 or later, Mac OS X v10.3.4 or later; unit dimensions: 3.5 x 1.6 x 0.27; unit weight: 1.5 ounces. ',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (10,'EN','EN','Zune is here. Designed around the principles of sharing, discovery and community, Zune will create new ways for people to connect and share entertainment experiences. The Zune experience centers around connection-- connection to your library, connection to friends, connection to community and connection to other devices. Zune starts with a 30GB digital media player and adds a twist. You can wirelessly share selected full-length sample tracks, playlists, pictures or your home-grown tracks directly from Zune to Zune. The Zune has arrived, sporting sharing features that may revolutionize the way we experience music. You can listen to the full-length songs that you receive up to three times in three days, flag the ones you like and easily buy them the next time you sync up. You can discover new music in the Zune Marketplace, and show off your favorite pictures and videos on the big, bright screen. Zune stores up to 7,500 songs, 25,000 pictures or 100 hours of video. You can make playlists on the go and watch a slide show while you''re listening. Watching video in landscape mode gets the most out of the vivid display. Zune has all that and a built in FM tuner, too. Zune comes in three colors: black, brown and white.',
    'The Digital Media Player reinvented. With the new Microsoft Zune you can wirelessly share selected full-length sample tracks, playlists, pictures or your home-grown tracks directly from Zune to Zune. Listen to those received full-length songs up to three times in three days, with the option to flag the ones you like to easily purchase them the next time you sync up. Browse the Zune Marketplace for access to millions of songs, old and new. Use the bright 3" LCD screen to watch your favorite videos or browse pictures of your family and friends. 30GB of storage means plenty of space for your music, photos, and videos. Never grow tired of your music with a built-in FM tuner for access to local FM radio broadcasts. Reinvent your digital media experience with the Microsoft Zune! Import unprotected music, photos and videos in WMA, MP3, AAC, JPEG, WMV, MPEG-4, H.264 from iTunes and Windows Media Player Purchase music from the continually updated Zune Marketplace using 79 Microsoft Points to purchase individual songs, or use a Zune Pass subscription for unlimited access to millions of songs for just $14.99 a month (Microsoft Points cards sold separately for purchasing music without a credit card) Optional Zune Car Pack allows you to play your tunes in your car with an FM transmitter with AutoSeek and Car Charger (Sold separately) Easily update your Zune via your PC when updates become available to add more features! Up to 12 hour battery life playing music with WiFi off Dimensions - 4.4 x 2.4 x 0.58 Weight - 5.6 ounces 1 Year limited manufacturer''s warranty Requires Windows XP with Service Pack 2 and High Speed Internet Connectivity',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (11,'EN','EN','Thin is definitely in. At just over a half-inch thick, the Motorola RAZR V3 is the perfect combination of sleek design and powerful features. And now you can get it dressed in gorgeous black. This special edition version kicks the style up a notch and demands attention. With long-range Bluetooth, support for video playback, a VGA (640 x 480) camera and a gorgeous color screen, the RAZR V3 is everything you''re looking for in a stylish mobile companion. Get the most out of your Cingular service with this impressive quad-band phone.',
    'The Moto Razr V3 is expertly crafted to deliver exceptional performance. Inside the ultra-thin design are advanced features like MPEG4 video playback, Bluetooth® wireless technology, a digital camera and more. And with the precision-cut keypad, minimalist styling and metal finish, the V3 looks just as beautiful as it performs. The real difference is in the details. See who’s calling, in color, without opening your phone — the large internal display is complemented by an impressive external display. The precision-cut metal keypad reacts to the lightest of touches. And the features you can''t always see are equally impressive, like quad-band GSM — for global calls where GSM network coverage and roaming agreements are present.',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (12,'EN','EN','The Creative Nomad MuVo² combines cutting-edge, high-capacity 1-inch hard disk drive storage, high-speed loading, and superb sound quality in a remarkably compact, easy-to-use package. Load up to 2,100 songs (based on 3.5 minutes per song, WMA/64 kbps with 4 GB storage) with simple plug-and-play, drag-and-drop functionality. Transfer any music or data files in a flash with super-fast USB 2.0. Enjoy high-fidelity sound with specifications unmatched by other MP3 and WMA players. The Nomad MuVo² is a perfect blend of capacity, style, versatility, and ease of use in a tiny player for the active music lover. Grab it, load it, and you''re all set to go!',
    'The Creative NOMAD MuVo? combines cutting-edge high capacity 1" hard disk drive storage, high-speed loading and superb sound quality in a remarkably compact, easy to use package. Load up to 2100 songs (based on 3.5 min per song, WMA / 64kbps with 4GB storage) with simple plug-and-play, drag-and-drop functionality. Transfer any music or data files in a flash with super fast USB2.0. Enjoy high fidelity sound with specifications unmatched by other MP3 and WMA players. The NOMAD MuVo? is a perfect blend of capacity, style, versatility and ease of use in a tiny player for the active music lover. Grab it, load it, clip it on your belt and you''re all set to go!',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (13,'EN','EN','SyNEt''s TBW-101UB Bluetooth USB Adapter allows you to make short-range wireless connections between your computer and Bluetooth enabled devices such as Cellular Phone, PDA, and Computer. It is compact and portable, eliminating the need for cables and physical connections between electronic devices. The Bluetooth USB Adapter transmission ensures both protection from interference and secured data transfers. Simply plug the USB Adapter into the USB port and enjoy the freedom and flexibility of Bluetooth wireless technology.',null,0, sysdate, 0, sysdate, 0);

Insert into PRODUCT_TRANSLATIONS values (23,'EN','EN','Includes: earbud headphones, USB 2.0 cable, dock adapter, case, iTunes for Windows and Mac, and more. Come one, come all and witness the incredible shrinking iPod! With the nano, Apple introduces the latest member of the highly successful iPod family of digital audio players. The nano is aptly named since it''s a fraction of the size of its larger iPod cousins. It is the width of a pencil and comes in at a feather-light 1.5 ounces. For Apple''s next trick, they''ve taken this new, diminutive iPod and added all of the features of a regular iPod. You get a bright, full-color display, Apple''s famous Click Wheel, and up to 14 hours of battery life. With that said, take a peek behind the curtain and be amazed at the rest of what the iPod nano has to offer: Connector for optional dock; stereo minijack; charge time: about 3 hours (1.5 hour fast charge to 80% capacity); AAC (16 to 320 Kbps); Protected AAC (from iTunes Music Store); MP3 (16 to 320 Kbps); MP3 VBR; Audible (formats 2, 3, and 4); Apple Lossless; WAV; AIFF; photo support: JPEG/BMP/GIF/TIFF/PSD (Mac only)/PNG; sync and charge via USB cable; adjust audiobook playback speed; create multiple on-the-go playlists; shuffle songs or albums; repeat one or all; 20 equalizer settings; backlight timer; display contrast; alarm; sleep timer; date and time; display time in menu bar; supports Windows 2000 with Service Pack 4 or later, Windows XP Home or Professional with Service Pack 2 or later, Mac OS X v10.3.4 or later; unit dimensions: 3.5 x 1.6 x 0.27; unit weight: 1.5 ounces. ',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (24,'EN','EN',
    'The world''s best-designed and easiest-to-use desktop just got faster. Now with the Intel Core Duo processor with two execution cores on a single chip--iMac brings a new generation of power to the amazing things it can do.','Includes: Apple Remote, Apple Keyboard, Mighty Mouse, Mac OS X v10.4 Tiger, iLife ''06, Front Row, and Photo Booth. 
    Apple iMac with Intel Core Duo - Never judge a book by it''s cover. A very appropriate phrase when talking about the new Apple iMac. On the outside it looks identical to the previous iMac desktop computer. The difference now lies at the heart of the latest iteration of the iMac. Powering the new all-in-one desktop is an Intel Core Duo! Dual processors on a single chip that gives you double the speed of the old iMac. With the new iMac you also get unique software applications. iLife ''06 is a suite of applications that will make your everyday life easier to manage than ever before. 
    And Front Row, combined with the included remote, lets you enjoy the media on your iMac from any seat in the house. Slot-loading 8x SuperDrive with 2.4x Dual Layer burning Write Speeds - up to 2.4x Dual Layer DVD+R, 8x DVD+R, 8x DVD-R, 4x DVD+RW, 4x DVD-RW, 24x CD-R, 8x CD-RW Read Speeds - up to 8x DVD-ROM, 24x CD-ROM Built-in 17 widescreen TFT active-matrix LCD Native Resolution - 1440x900 Built-in iSight webcam ATI Radeon X1600 graphics with 128MB of GDDR3 memory Ports - 10/100/1000Base-T Ethernet, 2 Firewire 400, 3 USB 2.0, 2 USB 1.1 (1 on keyboard), mini-DVI, DVI Out, VGA Out, S-Video Out, and Composite Out Built-in AirPort Extreme 802.11g Wi-Fi wireless network adapter Built-in Bluetooth 2.0+EDR Module Unit Weight - approx. 15.5 lbs.',
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (25,'EN','EN',
    'The world''s best-designed and easiest-to-use desktop just got faster. Now with the Intel Core Duo processor with two execution cores on a single chip--iMac brings a new generation of power to the amazing things it can do.','Includes: Apple Remote, Apple Keyboard, Mighty Mouse, Mac OS X v10.4 Tiger, iLife ''06, Front Row, and Photo Booth. 
    Apple iMac with Intel Core Duo - Never judge a book by it''s cover. A very appropriate phrase when talking about the new Apple iMac. On the outside it looks identical to the previous iMac desktop computer. The difference now lies at the heart of the latest iteration of the iMac. Powering the new all-in-one desktop is an Intel Core Duo! Dual processors on a single chip that gives you double the speed of the old iMac. With the new iMac you also get unique software applications. iLife ''06 is a suite of applications that will make your everyday life easier to manage than ever before. 
    And Front Row, combined with the included remote, lets you enjoy the media on your iMac from any seat in the house. Slot-loading 8x SuperDrive with 2.4x Dual Layer burning Write Speeds - up to 2.4x Dual Layer DVD+R, 8x DVD+R, 8x DVD-R, 4x DVD+RW, 4x DVD-RW, 24x CD-R, 8x CD-RW Read Speeds - up to 8x DVD-ROM, 24x CD-ROM Built-in 17 widescreen TFT active-matrix LCD Native Resolution - 1440x900 Built-in iSight webcam ATI Radeon X1600 graphics with 128MB of GDDR3 memory Ports - 10/100/1000Base-T Ethernet, 2 Firewire 400, 3 USB 2.0, 2 USB 1.1 (1 on keyboard), mini-DVI, DVI Out, VGA Out, S-Video Out, and Composite Out Built-in AirPort Extreme 802.11g Wi-Fi wireless network adapter Built-in Bluetooth 2.0+EDR Module Unit Weight - approx. 15.5 lbs.',
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (26,'EN','EN',
    'Live the digital life in stylish simplicity--up to five times faster. Just 6.5 inches square and 2 i nches small, Mac mini lets you have more fun with your music, photos and movies, more quickly and mo re easily. Enjoy them up close or far away with the included Apple Remote. The most affordable way t o Intel Core Duo, iLife ’06, and Front Row.',
    'Apple MA607LL/A Mac mini Desktop Computer - Apple is known around the world for its innovative computer design, and with the Mac mini they give you a powerful desktop computer in a case that''s roughly the size of a lunchbox. But this is the best looking lunchbox you''ve ever seen, with its sleek, anodized aluminum enclosure, slot-loading optical drive and an array of ports on the rear section that makes cable management a breeze. Inside the Mac mini, you''ll find a powerful Intel Core Duo Processor 1.66GHz, 512MB of PC2-5300 DDR2 SDRAM, a 60GB SATA Hard Drive, and much more. 60GB 5400RPM SATA HDD Slot-Loading DVD-ROM/CD-RW Combo Drive - (write speeds) up to 24x CD-R and 16x CD-RW Slot-Loading DVD-ROM/CD-RW Combo Drive - (read speeds) up to 8x DVD-ROM and 24x CD-ROM Intel GMA 950 graphics processor with 64MB of shared memory (memory is shared with the main system) 
    Ports - 10/100/1000 Gigabit Ethernet, 1 FireWire 400, 4 USB 2.0, 1 DVI Out, 1 VGA Out (w/ included adapter), 1 S-Video and Composite Video Out, combined Optical Digital Audio In/Audio Line In, and Combined Optical Digital Audio Out/Headphone Out Built-in Speakers Built-in AirPort Extreme 802.11g Wi-Fi Wireless Network Adapter Built-in Bluetooth 2.0+EDR (Enhanced Data Rate) module Unit Dimensions - 2 (h) x 6.5 (w) x 6.5 (d) Unit Weight - 2.9 lbs.',
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (27,'EN','EN','Miraculously engineered, the ultralight 17-inch PowerBook G4 is a mere 1-inch thin and only 6.9 pounds, making it one of the planet''s thinnest, lightest, 17-inch notebooks. The first thing you''ll notice is the megawide display -- the largest ever in a notebook. This PowerBook''s stunning display gives you the same viewing area as a 19-inch CRT monitor. And as for the amount of information you can see on the screen at one time, the 17-inch PowerBook supports a resolution of 1440 x 900 pixels -- an eye-popping 1.3 million pixels appearing on the screen simultaneously, with room aplenty for your menus, toolbars and palettes. Thanks to its built-in, dual-link DVI support and 128 MB of graphics memory, you even have the option of connecting your PowerBook to Apple''s breathtaking flat-panel displays, including the massive 30-inch Apple Cinema HD Display. Featuring a powerful 1.67 GHz PowerPC G4 processor, a standard 5400-rpm 100 GB hard drive, an 8x SuperDrive, up to 2 GB of DDR RAM and AirPort Extreme and Bluetooth 2.0+EDR built right in, the top gun of notebook computers has it all.',
    'Includes: lithium-ion battery, AC adapter, S-Video to Composite adapter, DVI to VGA adapter, iLife, iSync, and more. Apple 17" PowerBook Computer - This notebook computer comes packed with unique and convenient features that will greatly enhance your mobile computing experience. Built-in AirPort Extreme is a great feature to help keep you connected on the road. Wherever there''s a Wi-Fi Hot Spot, you can wirelessly surf the Internet and check e-mail. And if there''s no Wi-Fi around, you can use a Bluetooth-enabled cell phone as a modem, thanks to built-in Bluetooth 2.0 support. With Bluetooth 2.0, you can also use it along with iSync, to keep your contacts and schedules up to date. Not to mention enjoying a cable-free experience with an optional Apple wireless keyboard and mouse! Another really unique feature is the trackpad. Unlike other trackpads, this trackpad lets you easily scroll through web pages and large documents using a unique 2-finger method. ATI Mobility Radeon 9700 with 128MB of DDR SDRAM and dual-link DVI 100GB 5400RPM HDD SuperDrive - up to 8x DVD-R, 4x DVD-RW, 8x DVD+R, 4x DVD+RW, 24x CD-R, 10x CD-RW, 24x CD-ROM, and 8x DVD-ROM Built-in Gigabit Ethernet - 10/100/1000 Built-in 802.11g AirPort Extreme Built-in Bluetooth 2.0+EDR (Enhanced Data Rate) Built-in 56k v.92 Fax Modem Full size illuminated keyboard with ambient light sensor Unit Dimensions - 1 (h) x 15.4 (w) x 10.2 (d) Unit Weight - 6.9 lbs.',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (28,'EN','EN','Powered by a dual-core Intel engine. Up to four times the speed of the PowerBook G4. Eight times the graphics bandwidth. With built-in iSight for instant video conferencing on the move. And Front Row with Apple Remote to dazzle everyone in the room. Wait no more.',
    'You''ve seen improvements in notebook performance before - but never on this scale. The Intel Core Duo powering MacBook Pro is actually two processors built into a single chip. This, combined with myriad other engineering leaps, boosts performance up to four times higher than the PowerBook G4. With this awesome power, it''s a breeze to render complex 3D models, enjoy smooth playback of HD video, or host a four-way video conference.Intel Core Duo is the first chip built using Intel''s groundbreaking 65-nanometer process - resulting in transistors so small, you could fit a hundred inside a single human cell. With smaller distances for electrons to travel, and two processors designed to share resources and conserve power, Intel Core Duo achieves higher levels of performance as it uses fewer watts. Which is what makes it possible to design a super-powerful MacBook Pro that''s only one inch thin.When Mac technology makes something easy, it''s hardly news. So here''s more non-news for MacBook Pro owners: software just works. If you see the Universal logo on a new application, that means it will run on Intel- and PowerPC-based Mac computers. For most existing applications, you simply do what you''ve always done: double-click them. Thanks to the Rosetta technology in Mac OS X, they look and feel just like they did before.',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (29,'EN','EN',
    'The sleekly styled 32-inch Nexus HD-ready monitor features the company''s latest LCD panel technology--Cinespeed--and an expanded viewing angle of 176 degrees. With no internal tuner (either standard NTSC or digital ATSC), the 32HLC56 requires an optional tuner or cable/satellite set-top box to receive standard- and high-definition television programming. 
    It''s easy to connect to brilliant imagery with the component and HDMI connections--the latter offering pure digital audio/video performance with no degradation of signal from just one convenient cable. This set also offers Nexus''s exclusive HD Dynamic Contrast function, which provides a sharper, deeper image with rich colors and a more life-like image.',null,
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (30,'EN','EN',
    'Be prepared to capture that elusive moment anytime, anywhere with the SC-MM10S Ultra Compact MemoryCam. It packs a 10x optical/100x digital zoom and 680K pixel CCD with electronic image stabilization for remarkably clear pictures, viewed in the 2.0-inch LCD display. The 512MB memory can be expanded via the SD/MMC slot. 
    In addition to USB 2.0/PictBridge for printing stills, it offers MP3/webcam/voice recorder and data storage capabilities.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (31,'EN','EN','The simple to use Kodi EasyShare C743 zoom digital camera provides remarkable features at a reasonable price. You''ll bring details to life with 7.1-megapixel resolution. And the C743 has a 3x optical zoom lens and a huge 2.4-inch color display, proving that impressive doesn''t always need to be expensive.',
    'The simple to use Kodak EasyShare C743 zoom digital camera provides remarkable features at a reasonable price. You''ll bring details to life with 7.1 Megapixel and the C743 has a 3x optical zoom lens, huge 2.5 inch color display. Capture life in motion with continuous VGA video 640x480 at 30 fps, featuring audio capture and playback. Create your perfect picture without a computer, using on-camera cropping. Know your pictures are in focus with the blurry picture alert feature. Restore an unintentionally deleted picture with the undo-delete function. Automatically reduce red-eye during picture capture with digital red-eye reduction. The C743 is part of the Kodak EasyShare system, so printing and sharing your pictures is amazingly simple. Shutter speed - 4-1/1400 seconds, long exposure 4 seconds max 2.5 inch LCD indoor/outdoor color display Optical Real Image Viewfinder Self timer - 2 and 10 seconds, 2 shot and burst Scene modes - auto, portrait, sport, landscape, night portrait, snow, beach, fireworks, self portrait, close up, backlight, children, party Still format - JPEG/EXIF v 2.21 QuickTime MOV MPEG-4 format with audio recording during capture NTSC or PAL I/O interface Tripod mount 1/4 inch standard System requirements - Windows XP, 2000 SP4 or later, 600 MHz processor or greater; Internet Explorer 6.0 or higher, Macintosh OS X 10.3 or higher; Safari 1.1 or higher, 128 MB RAM, 200 MB hard drive disk space available, CD-ROM drive, available USB port, color monitor, 800 x 600 display resolution, 16-bit minimum Unit Dimensions - Width 3.6 x Height 2.3 x Depth 1.3 inch, 92.2 x 65.7 x 32.4 mm Weight without batteries - 145 grams (5.1 ounces)',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (32,'EN','EN','The Pan/Tilt IP Camera is a full-featured surveillance system that provides high quality video over a wireless network connection. Built-in CPU and Web Server allow the camera to function as a standalone device, allowing users to access the camera anywhere in the world by using a Web browser. Users can also move the camera remotely in almost any direction, scanning sensitive locations for unauthorized intrusion. The IP Camera comes with a CMOS sensor to deliver clear and crisp images, and its powerful IPView software gives users enhanced security options to archive streaming video straight to a computer''s hard drive. IP View software can also monitor multiple cameras on a single screen, enable motion detection to trigger automatic recording, and send email alert notification.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (33,'EN','EN','LG''s newest mobile treat, the VX-8500 Chocolate offers minimalist-inspired style and a silky-smooth slider design. Deluxe features include support for V Cast Music, glowing touch-sensitive navigation keys, a powerful integrated music/video player, a 1.3 megapixel camera/camcorder, stereo Bluetooth capabilities, and a microSD memory slot for extra storage. If you value extreme style mixed with powerful substance, this is the phone for you.',
    'So what makes the Chocolate look so great? The touch sensitive keypad controls? The sliding number pad? Slim design? Beautiful screen? From RandB to Heavy Metal to Easy Listening, the Chocolate lets you download from over 1 million songs on the go with V CAST music.',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (34,'EN','EN',
    'UIX''s A6 cameras come with very advanced features, but at a very affordable price. In addition to the true digital still picture color and sharpness you''d expect from this camera''s 6-megapixel image sensor, you also have a built-in Power Movie Clip function that lets you choose between 30 or 15 frames per second. And, it''s easy to double check your recently shot video with highly convenient pause, fast forward, and/or rewind right in the camera. 
    The A6''s shutter button toggles between capture and playback modes, a great innovation for instant review of the pic you just took. Another one touch button allows you to take charge with manual, aperture priority, and shutter priority modes. Speaking of convenience, there''s even a built in mirror, so you can see how you look when you take your own picture! Select from six different image sizes from 640 by 480 pixels to 2,816 by 2,112 pixels and from three resolution ranges--superfine, fine, and normal for 18 different resolution/size combinations--a useful memory management tool. 
    For example, you can take a postage stamp size picture from only 1.58 inches away in high resolution for wonderful color printing output, or a large but lower resolution landscape picture for full-screen sharing without choking friends'' e-mail. Samsung''s in-camera editing capabilities include the ability to crop, rotate, and make numerous color revisions. Included are ArcSoft Photo Impression, Digimax Viewer and Digimax Reader software for editing, storage and USB connection output to your PC or directly to your printer via the included USB cable.',null,
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (35,'EN','EN',
    'You''ll be amazed at the small, sleek form factor of the BlackBerry Pearl. It''s like no other BlackBerry. But it''s more than just a new look. This BlackBerry delivers everything its predecessors delivered and a whole lot more. The BlackBerry Pearl offers new features never before seen in a BlackBerry like, a 1.3 mega pixel camera, voice recognition, and an MP3 player to name a few. Try it for a few hours and you are hooked!',null,
    0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (36,'EN','EN','Nintendo''s Wii video game system (pronounced "we") is designed to attract people, regardless of their age or video game experience, to sit down and play together--whether they''re in the same room or on different sides of the globe. The system''s name reflects this simple idea. It''s easily pronounced in a variety of languages, and the distinctive spelling suggests two players side by side. The two Wii features Nintendo thinks will create new levels of gaming community are built-in Wi-Fi access, supported by a new online gaming service, and Wii''s intuitive, wireless, motion-sensitive game controller.',
    'MODEL- WII VENDOR- NINTENDO FEATURES- Wii Console The sleek Wii console, no larger than a stack of several DVD cases, includes Wii Sports, a sensor bar, an AV cable, a Wii stand, a Wii Remote, and a Nunchuk controller for even more exciting game- control possibilities. Featuring a remarkable wireless controller experience, the Nintendo Wii console invites players into game worlds and activities like never before. Whether theyre young or old, expert gamers or beginners, Wii players will express themselves with intuitive motion control using the Wii Remote: a flick of the wrist to swing a baseball bat or tennis racket, a backswing and follow-through to send a golf ball flying over a pristine fairway. Wii Sports, packaged with the Wii console, introduces players to those and many other experiences. Wii also taps into Nintendos unrivaled legacy of great games with the Virtual Console. Connecting via wireless broadband to Nintendo Wi-Fi Connection, Wii owners will be able to spend Virtual Console points to download selected classic games from NES, Super NES and N64 video game consoles. And through WiiConnect24, owners will be able to access even more content. Four-player compatibility as well as the ability to compete with other Wii players over broadband internet means that Wii offers a true social experience. * Design Featuring a compact design that makes it a natural addition to any television setup, the Wii console is white in color and can be displayed either vertically or horizontally. * GameCube Compatibility The Wii is backward-compatible to all Nintendo GameCube games',0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (37,'EN','EN','To make gaming as accessible to people of all ages and all abilities, Nintendo wanted to create a controller that was as inviting as it was sophisticated. The outcome is the Wii Remote controller. Nintendo fused the familiarity of a remote control with the sophistication of motion-sensing technology to come up with an input device for the ages!Sporting the size of a traditional remote control, the wireless Wii Remote controller is a multifunctional device that is limited only by the game designer''s imagination. In a tennis game, it serves as your racket you swing with your arm. In a driving game, it serves as your steering wheel. For first-person shooters, the remote acts as your weapon that you point at an enemy. The list of potential uses goes on and on.Using Bluetooth technology, the wireless Wii Remote controller sends your actions to the Wii console from as far as 30 feet away. As a pointing device, the controller can send a signal from as far as 15 feet away. Up to four Wii Remote Controllers can be connected at once, making for some great multiplayer fun!',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (38,'EN','EN','EJB 3.0 has made huge advances in ease of development, and its drastically simplified programming model has been widely acclaimed. Targeted at Java and J2EE developers both with and without prior EJB experience, Beginning EJB 3 Application Development takes readers through the details of the EJB 3.0 architecture, and shows how EJB can be used to develop powerful, standards-based backend business logic. With 12 years of combined EJB experience, the authors offer many practical insights into the entire EJB architecture and cover all areas of the EJB 3.0 specification',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (39,'EN','EN','EJB 3.0 sets a new precedent. It has made huge advances in ease of development, and its drastically simplified programming model has been widely acclaimed. This book is the definitive guide to EJB 3.0 persistence technology. The authors provide unparalleled insight and expertise on this topic, fully examining and explaining EJB 3.0 persistence specification. They describe how to use this sophisticated technology to its full potential',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (40,'EN','EN',
    'Get a thorough understanding of Oracle Database 10g from the most comprehensive Oracle database reference on the market, published by Oracle Press. From critical architecture concepts to advanced object-oriented concepts, this powerhouse contains nearly 50 chapters designed to enlighten you. 
    Upgrade from earlier versions, use SQL, SQL Plus, and PL/SQL. Get code examples and access popular documentation PDFs--plus a full electronic copy of the book on the included CD-ROM. 
    Go beyond the basics and learn security, text searches, external tables, using Java in Oracle, and a great deal more',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (41,'EN','EN',
    'EJB 3 in Action tackles EJB 3 and the Java Persistence API head-on, providing practical code samples, real-life scenarios, best practices, design patterns, and performance tuning tips. This book builds on the contributions and strengths of seminal technologies like Spring, Hibernate, and TopLink. EJB 3 is the most important innovation introduced in Java EE 5.0. EJB 3 simplifies enterprise development, abandoning the complex EJB 2.x model in favor of a lightweight POJO framework. 
    The new API represents a fresh perspective on EJB without sacrificing the mission of enabling business application developers to create robust, scalable, standards-based solutions. 
    EJB 3 in Action is a fast-paced tutorial, geared toward helping you learn EJB 3 and the Java Persistence API quickly and easily. For newcomers to EJB, this book provides a solid foundation in EJB. For the developer moving to EJB 3 from EJB 2, this book addresses the changes both in the EJB API and in the way the developer should approach EJB and persistence. ',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (42,'EN','EN','It is not possible to fit 36 Bach masterpieces on two CDs, so what Essential Bach does is present individual movements from across a range of the composer''s work. The anthology is clearly aimed at the newcomer, and the absence of booklet notes to put the music in context is disappointing. We are only given titles, performers, and what films the extracts have been featured in, from Rollerball to The English Patient. On the plus side, most if not all of the music is instantly recognizable, by melody if not by name. Everything from the Brandenburg Concertos to "Air on a G String" to the B Minor Mass and St. Matthew Passion is represented. Performances range from 1960 to 1993, encompassing both early instrument and modern orchestra interpretations by a wide variety of forces, including Sir Neville Marriner with the Academy of St. Martin in the Fields and Raymond Leppard leading the English Chamber Orchestra. Given such diversity the result is unavoidably a patchwork, albeit one made from the finest materials, and as such is perhaps best treated as a sampler to aid exploration of the vast legacy of one of the very greatest composers who ever lived. ',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (43,'EN','EN','These are thoroughly balanced and lovingly conceived performances. They reveal great strength of character, healthy self-control and mature insight. Ferencsik evidently had experienced much, with emotional and spiritual roots that went deep. Consequently he had no need to resort to surface, superficial excitement to compensate for lack of insight. Ferencsik reveals the mature insight that comes only from a life-long contemplation of scores that the conductor knew as well as he knew the date of his own birthday.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (44,'EN','EN','This 2CDs set is quite a good compilation of arias from Mozart''s best known operas. The cast is awesome, too. The trouble is Mozart wrote so many wonderful arias that when you try to compile them from many operas, lots of the great ones like ''Non piu di fiori'' and ''Deh per questo istante solo'' from La clemenza di Tito get left out (tho having Teresa Berganza''s version of ''Parto ma tu ben mio'' makes up for it somewhat). A lot of chorus pieces from Idomeneo but none of Idamante''s arias, no Elettra''s famous rage aria, and no ''Traurigkeit'' from ''Die Entfuehrung''? Bottom line, all the arias included are marvellously sung. I think the line up could have been better, tho. It won''t fill you up, perhaps, but it will wet your appetite for complete set of the operas included.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (45,'EN','EN','In this recording we hear one of the great piano performers in Vladimir Ashkenazy playing pieces from one of the greatest piano composers in Fryderyk Chopin; with the utmost quality in recorded sound. And if one needs more convincing, you get two hours of music for the price of one cd. Hard to find a better buy in classical music. Moreover, this cd not only looks good on paper, but it also is one of my favorites to listen to. I usually listen to music to help enrich and exonerate an otherwise mundane (computer) task, and I find myself stopping work several times each listen because I''m overcome by the beauty of these pieces, and the both spirited and soulful playing of Ashkenazy. For anyone new to Chopin, I cannot think of a better starting point (no, this double cd does not cover all his great compositions!) than this recording.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (46,'EN','EN',
    'We haven''t had a disc of Tchaikovsky ballet excerpts from the Vienna Phil., I believe, since Karajan''s four decades ago (a great recording on Decca in plush remastered sound). Here under James Levine in 1992 the orchestra is even better--more fluid, sparkling and alive than under Karajan. This is well-worn music that every collector already owns, and it''s easy to overlook Levine as a Tchaikovsky conductor. 
    Here he defies all expectations. True, he doesn''t take a balletic aproach. Levine''s tempos in general are too fast to dance to. But in the symphonic vein he has chosen, Levine works miracles. The urgent virtuosity of the playing--aided by excellent recorded sound--is jaw-dropping, and the violin soloist in the long Swan Lake scene (#4) is beyond compare for delicacy and poetry. Karajan''s only fault in this music wass to blow it up out of proportion; Previn''s was to apply routine phrasing. 
    Levine makes these suites totally riveting and sensuously luxurious without any trace of pomposity. Highly recommended.',null,0, sysdate, 0, sysdate, 0);
Insert into PRODUCT_TRANSLATIONS values (47,'EN','EN',
    'CD 1 THE THREE GREAT SYMPHONIES CD 1 Symphony No. 7 in D Minor, Op. 70 q. I. Allegro maestoso 2. Poco adagio 3. Scherzo: Vivance 4. Finale: Allegro Symphony No. 8 in G Mahor, Op. 88 5. Allegro con brio 6. Adagio 7. Allegretto grazioso 8. Allegro, ma non troppo CD 2. Symphony No. 9 in E Minor, Op. 95 1. Adagio; allegro molto 2. Largo 3. Scherzo: Molto vivace 4. Alllegro con fuoco 5. Scherzo capriccioso, Op. 66.',null,0, sysdate, 0, sysdate, 0);
    
-- Clone for alternative languages    
insert into product_translations select product_id, 'JA', 'EN', description, additional_info,0,sysdate,0,sysdate,0 from product_translations where language='EN';
insert into product_translations select product_id, 'EL', 'EN', description, additional_info,0,sysdate,0,sysdate,0 from product_translations where language='EN';
insert into product_translations select product_id, 'FR', 'EN', description, additional_info,0,sysdate,0,sysdate,0 from product_translations where language='EN';
insert into product_translations select product_id, 'DE', 'EN', description, additional_info,0,sysdate,0,sysdate,0 from product_translations where language='EN';


