REM Define the product categories for seeded products
REM $Id: PRODUCT_CATEGORIES_BASE.sql 888 2007-03-01 16:27:31Z drmills $

INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (2, null, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (3, null, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (1, null, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (8, 1, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (9, 1, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (10, 1, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (11, 1, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (12, 2, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (13, 2, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (14, 2, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (4, 3, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (5, 3, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (6, 3, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
INSERT INTO PRODUCT_CATEGORIES_BASE VALUES (7, 3, 'N', null, 0, SYSDATE, 0, SYSDATE, 1);
