package oracle.foddemo.masterpricelist.model.service.client;

import oracle.foddemo.masterpricelist.model.service.common.MasterPriceListService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 03 15:17:30 PST 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MasterPriceListServiceClient extends ApplicationModuleImpl implements MasterPriceListService {
    /**
     * This is the default constructor (do not remove).
     */
    public MasterPriceListServiceClient() {
    }

    public String getConnectedUser() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getConnectedUser",null,null);
        return (String)_ret;
    }
}
