package devguide.advanced.baseproject.extsub.client;

import devguide.advanced.baseproject.extsub.common.ProductsByNameRow;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductsByNameRowClient extends ProductsRowClient implements ProductsByNameRow {
    /**This is the default constructor (do not remove).
     */
    public ProductsByNameRowClient() {
    }


    public void setProductName(String value) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setProductName",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }

    public void setProductId(Number value) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setProductId",new String [] {"oracle.jbo.domain.Number"},new Object[] {value});
        return;
    }

    public void setCheckSum(String value) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setCheckSum",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }

    public String getProductName() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getProductName",null,null);
        return (String)_ret;
    }

    public Number getProductId() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getProductId",null,null);
        return (Number)_ret;
    }

    public String getCheckSum() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getCheckSum",null,null);
        return (String)_ret;
    }

    public void someExtraFeature(String x) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"someExtraFeature",new String [] {"java.lang.String"},new Object[] {x});
        return;
    }
}
