package devguide.advanced.baseproject.extsub.client;

import devguide.advanced.baseproject.extsub.common.Products;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductsClient extends ViewUsageImpl implements Products {
    /**This is the default constructor (do not remove).
     */
    public ProductsClient() {
    }

    public void someCustomMethodOnProducts(String arg) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"someCustomMethodOnProducts",new String [] {"java.lang.String"},new Object[] {arg});
        return;
    }
}
