package devguide.advanced.customprops;

import oracle.jbo.AttributeDef;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductDefImpl extends EntityDefImpl {
    /**This is the default constructor (do not remove).
     */
    public ProductDefImpl() {
    }  
    
    protected void createDef() {
    super.createDef();
    setProperty("EntityCustomProperty","EntityCustomPropertyValue");
    AttributeDef attrDef = findAttributeDef("ProductName");
    ((AttributeDefImpl)attrDef).setProperty("ProductNameAttrCustomProperty",
                                            "ProductNameAttrCustomPropertyValue");
  }
}
