package oracle.fodemo.storefront.store.queries;


import oracle.fodemo.storefront.entities.OrderEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrdersVORowImpl extends ViewRowImpl {
    public static final int VIEWATTR = 26;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OrderId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderId((DBSequence)value);
            }
        }
        ,
        OrderDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderDate((Date)value);
            }
        }
        ,
        OrderShippedDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderShippedDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderShippedDate((Date)value);
            }
        }
        ,
        OrderStatusCode {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderStatusCode();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderStatusCode((String)value);
            }
        }
        ,
        OrderTotal {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderTotal();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setOrderTotal((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        ShipToName {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShipToName();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShipToName((String)value);
            }
        }
        ,
        ShipToAddressId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShipToAddressId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShipToAddressId((Number)value);
            }
        }
        ,
        ShipToPhoneNumber {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShipToPhoneNumber();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShipToPhoneNumber((String)value);
            }
        }
        ,
        ShippingOptionId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShippingOptionId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShippingOptionId((Number)value);
            }
        }
        ,
        PaymentOptionId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getPaymentOptionId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setPaymentOptionId((Number)value);
            }
        }
        ,
        DiscountId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getDiscountId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setDiscountId((Number)value);
            }
        }
        ,
        CouponId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCouponId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCouponId((Number)value);
            }
        }
        ,
        FreeShippingFlag {
            public Object get(OrdersVORowImpl obj) {
                return obj.getFreeShippingFlag();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setFreeShippingFlag((String)value);
            }
        }
        ,
        CustomerCollectFlag {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCustomerCollectFlag();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCustomerCollectFlag((String)value);
            }
        }
        ,
        CollectionWarehouseId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCollectionWarehouseId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCollectionWarehouseId((Number)value);
            }
        }
        ,
        GiftwrapFlag {
            public Object get(OrdersVORowImpl obj) {
                return obj.getGiftwrapFlag();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setGiftwrapFlag((String)value);
            }
        }
        ,
        GiftwrapMessage {
            public Object get(OrdersVORowImpl obj) {
                return obj.getGiftwrapMessage();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setGiftwrapMessage((String)value);
            }
        }
        ,
        CalculatedOrderTotal {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCalculatedOrderTotal();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCalculatedOrderTotal((Double)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(OrdersVORowImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setObjectVersionId((Number)value);
            }
        }
        ,
        TotalShippingCost {
            public Object get(OrdersVORowImpl obj) {
                return obj.getTotalShippingCost();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setTotalShippingCost((Double)value);
            }
        }
        ,
        DiscountAmount {
            public Object get(OrdersVORowImpl obj) {
                return obj.getDiscountAmount();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setDiscountAmount((Double)value);
            }
        }
        ,
        InvoiceTotal {
            public Object get(OrdersVORowImpl obj) {
                return obj.getInvoiceTotal();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setInvoiceTotal((Double)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        TypedCouponCode {
            public Object get(OrdersVORowImpl obj) {
                return obj.getTypedCouponCode();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setTypedCouponCode((String)value);
            }
        }
        ,
        ShipToAddressId1 {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShipToAddressId1();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setShipToAddressId1((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(OrdersVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        isCancelable {
            public Object get(OrdersVORowImpl obj) {
                return obj.getisCancelable();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setisCancelable((Boolean)value);
            }
        }
        ,
        isPublishableEvent {
            public Object get(OrdersVORowImpl obj) {
                return obj.getisPublishableEvent();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setisPublishableEvent((Boolean)value);
            }
        }
        ,
        AddressesVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getAddressesVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrderItemsVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getOrderItemsVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShippingOptionsVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShippingOptionsVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentOptionsVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getPaymentOptionsVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShippingOptions {
            public Object get(OrdersVORowImpl obj) {
                return obj.getShippingOptions();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Addresses {
            public Object get(OrdersVORowImpl obj) {
                return obj.getAddresses();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentOptions {
            public Object get(OrdersVORowImpl obj) {
                return obj.getPaymentOptions();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AddressesAndUsagesVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getAddressesAndUsagesVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MembershipDiscountsVO {
            public Object get(OrdersVORowImpl obj) {
                return obj.getMembershipDiscountsVO();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Coupons {
            public Object get(OrdersVORowImpl obj) {
                return obj.getCoupons();
            }

            public void put(OrdersVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;

        private static int firstIndex = 0;

        /**
         * @param object
         * @return
         */
        public abstract Object get(OrdersVORowImpl object);

        /**
         * @param object
         * @param value
         */
        public abstract void put(OrdersVORowImpl object, Object value);

        /**
         * @return
         */
        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        /**
         * @return
         */
        public static int firstIndex() {
            return firstIndex;
        }

        /**
         * @return
         */
        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        /**
         * @return
         */
        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ORDERID = AttributesEnum.OrderId.index();
    public static final int ORDERDATE = AttributesEnum.OrderDate.index();
    public static final int ORDERSHIPPEDDATE = AttributesEnum.OrderShippedDate.index();
    public static final int ORDERSTATUSCODE = AttributesEnum.OrderStatusCode.index();
    public static final int ORDERTOTAL = AttributesEnum.OrderTotal.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int SHIPTONAME = AttributesEnum.ShipToName.index();
    public static final int SHIPTOADDRESSID = AttributesEnum.ShipToAddressId.index();
    public static final int SHIPTOPHONENUMBER = AttributesEnum.ShipToPhoneNumber.index();
    public static final int SHIPPINGOPTIONID = AttributesEnum.ShippingOptionId.index();
    public static final int PAYMENTOPTIONID = AttributesEnum.PaymentOptionId.index();
    public static final int DISCOUNTID = AttributesEnum.DiscountId.index();
    public static final int COUPONID = AttributesEnum.CouponId.index();
    public static final int FREESHIPPINGFLAG = AttributesEnum.FreeShippingFlag.index();
    public static final int CUSTOMERCOLLECTFLAG = AttributesEnum.CustomerCollectFlag.index();
    public static final int COLLECTIONWAREHOUSEID = AttributesEnum.CollectionWarehouseId.index();
    public static final int GIFTWRAPFLAG = AttributesEnum.GiftwrapFlag.index();
    public static final int GIFTWRAPMESSAGE = AttributesEnum.GiftwrapMessage.index();
    public static final int CALCULATEDORDERTOTAL = AttributesEnum.CalculatedOrderTotal.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();
    public static final int TOTALSHIPPINGCOST = AttributesEnum.TotalShippingCost.index();
    public static final int DISCOUNTAMOUNT = AttributesEnum.DiscountAmount.index();
    public static final int INVOICETOTAL = AttributesEnum.InvoiceTotal.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int TYPEDCOUPONCODE = AttributesEnum.TypedCouponCode.index();
    public static final int SHIPTOADDRESSID1 = AttributesEnum.ShipToAddressId1.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int ISCANCELABLE = AttributesEnum.isCancelable.index();
    public static final int ADDRESSESVO = AttributesEnum.AddressesVO.index();
    public static final int ORDERITEMSVO = AttributesEnum.OrderItemsVO.index();
    public static final int PAYMENTOPTIONSVO = AttributesEnum.PaymentOptionsVO.index();
    public static final int SHIPPINGOPTIONSVO = AttributesEnum.ShippingOptionsVO.index();
    public static final int SHIPPINGOPTIONS = AttributesEnum.ShippingOptions.index();
    public static final int ADDRESSES = AttributesEnum.Addresses.index();
    public static final int PAYMENTOPTIONS = AttributesEnum.PaymentOptions.index();
    public static final int ADDRESSESANDUSAGESVO = AttributesEnum.AddressesAndUsagesVO.index();
    public static final int MEMBERSHIPDISCOUNTSVO = AttributesEnum.MembershipDiscountsVO.index();
    public static final int COUPONS = AttributesEnum.Coupons.index();

    public static final int ISPUBLISHABLEEVENT = AttributesEnum.isPublishableEvent.index();

    /**This is the default constructor (do not remove).
     */
    public OrdersVORowImpl() {
    }

    /**Gets OrderEO entity object.
     * @return
     */
    public OrderEOImpl getOrderEO() {
        return (OrderEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ORDER_ID using the alias name OrderId.
     * @return
     */
    public DBSequence getOrderId() {
        return (DBSequence)getAttributeInternal(ORDERID);
    }

    /**Sets <code>value</code> as attribute value for ORDER_ID using the alias name OrderId.
     * @param value
     */
    public void setOrderId(DBSequence value) {
        setAttributeInternal(ORDERID, value);
    }

    /**Gets the attribute value for ORDER_DATE using the alias name OrderDate.
     * @return
     */
    public Date getOrderDate() {
        return (Date) getAttributeInternal(ORDERDATE);
    }

    /**Sets <code>value</code> as attribute value for ORDER_DATE using the alias name OrderDate.
     * @param value
     */
    public void setOrderDate(Date value) {
        setAttributeInternal(ORDERDATE, value);
    }

    /**Gets the attribute value for ORDER_SHIPPED_DATE using the alias name OrderShippedDate.
     * @return
     */
    public Date getOrderShippedDate() {
        return (Date) getAttributeInternal(ORDERSHIPPEDDATE);
    }

    /**Sets <code>value</code> as attribute value for ORDER_SHIPPED_DATE using the alias name OrderShippedDate.
     * @param value
     */
    public void setOrderShippedDate(Date value) {
        setAttributeInternal(ORDERSHIPPEDDATE, value);
    }

    /**Gets the attribute value for ORDER_STATUS_CODE using the alias name OrderStatusCode.
     * @return
     */
    public String getOrderStatusCode() {
        return (String) getAttributeInternal(ORDERSTATUSCODE);
    }

    /**Sets <code>value</code> as attribute value for ORDER_STATUS_CODE using the alias name OrderStatusCode.
     * @param value
     */
    public void setOrderStatusCode(String value) {
        setAttributeInternal(ORDERSTATUSCODE, value);
    }

    /**Gets the attribute value for ORDER_TOTAL using the alias name OrderTotal.
     * @return
     */
    public Number getOrderTotal() {
        return (Number) getAttributeInternal(ORDERTOTAL);
    }

    /**Sets <code>value</code> as attribute value for ORDER_TOTAL using the alias name OrderTotal.
     * @param value
     */
    public void setOrderTotal(Number value) {
        setAttributeInternal(ORDERTOTAL, value);
    }

    /**Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**Gets the attribute value for SHIP_TO_NAME using the alias name ShipToName.
     * @return
     */
    public String getShipToName() {
        return (String) getAttributeInternal(SHIPTONAME);
    }

    /**Sets <code>value</code> as attribute value for SHIP_TO_NAME using the alias name ShipToName.
     * @param value
     */
    public void setShipToName(String value) {
        setAttributeInternal(SHIPTONAME, value);
    }

    /**Gets the attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId.
     * @return
     */
    public Number getShipToAddressId() {
        return (Number) getAttributeInternal(SHIPTOADDRESSID);
    }

    /**Sets <code>value</code> as attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId.
     * @param value
     */
    public void setShipToAddressId(Number value) {
        setAttributeInternal(SHIPTOADDRESSID, value);
    }

    /**Gets the attribute value for SHIP_TO_PHONE_NUMBER using the alias name ShipToPhoneNumber.
     * @return
     */
    public String getShipToPhoneNumber() {
        return (String) getAttributeInternal(SHIPTOPHONENUMBER);
    }

    /**Sets <code>value</code> as attribute value for SHIP_TO_PHONE_NUMBER using the alias name ShipToPhoneNumber.
     * @param value
     */
    public void setShipToPhoneNumber(String value) {
        setAttributeInternal(SHIPTOPHONENUMBER, value);
    }

    /**Gets the attribute value for SHIPPING_OPTION_ID using the alias name ShippingOptionId.
     * @return
     */
    public Number getShippingOptionId() {
        return (Number) getAttributeInternal(SHIPPINGOPTIONID);
    }

    /**Sets <code>value</code> as attribute value for SHIPPING_OPTION_ID using the alias name ShippingOptionId.
     * @param value
     */
    public void setShippingOptionId(Number value) {
        setAttributeInternal(SHIPPINGOPTIONID, value);
    }

    /**Gets the attribute value for PAYMENT_OPTION_ID using the alias name PaymentOptionId.
     * @return
     */
    public Number getPaymentOptionId() {
        return (Number) getAttributeInternal(PAYMENTOPTIONID);
    }

    /**Sets <code>value</code> as attribute value for PAYMENT_OPTION_ID using the alias name PaymentOptionId.
     * @param value
     */
    public void setPaymentOptionId(Number value) {
        setAttributeInternal(PAYMENTOPTIONID, value);
    }

    /**Gets the attribute value for DISCOUNT_ID using the alias name DiscountId.
     * @return
     */
    public Number getDiscountId() {
        return (Number) getAttributeInternal(DISCOUNTID);
    }

    /**Sets <code>value</code> as attribute value for DISCOUNT_ID using the alias name DiscountId.
     * @param value
     */
    public void setDiscountId(Number value) {
        setAttributeInternal(DISCOUNTID, value);
    }

    /**Gets the attribute value for COUPON_ID using the alias name CouponId.
     * @return
     */
    public Number getCouponId() {
        return (Number) getAttributeInternal(COUPONID);
    }

    /**Sets <code>value</code> as attribute value for COUPON_ID using the alias name CouponId.
     * @param value
     */
    public void setCouponId(Number value) {
        setAttributeInternal(COUPONID, value);
    }

    /**Gets the attribute value for FREE_SHIPPING_FLAG using the alias name FreeShippingFlag.
     * @return
     */
    public String getFreeShippingFlag() {
        return (String) getAttributeInternal(FREESHIPPINGFLAG);
    }

    /**Sets <code>value</code> as attribute value for FREE_SHIPPING_FLAG using the alias name FreeShippingFlag.
     * @param value
     */
    public void setFreeShippingFlag(String value) {
        setAttributeInternal(FREESHIPPINGFLAG, value);
    }

    /**Gets the attribute value for CUSTOMER_COLLECT_FLAG using the alias name CustomerCollectFlag.
     * @return
     */
    public String getCustomerCollectFlag() {
        return (String) getAttributeInternal(CUSTOMERCOLLECTFLAG);
    }

    /**Sets <code>value</code> as attribute value for CUSTOMER_COLLECT_FLAG using the alias name CustomerCollectFlag.
     * @param value
     */
    public void setCustomerCollectFlag(String value) {
        setAttributeInternal(CUSTOMERCOLLECTFLAG, value);
    }

    /**Gets the attribute value for COLLECTION_WAREHOUSE_ID using the alias name CollectionWarehouseId.
     * @return
     */
    public Number getCollectionWarehouseId() {
        return (Number) getAttributeInternal(COLLECTIONWAREHOUSEID);
    }

    /**Sets <code>value</code> as attribute value for COLLECTION_WAREHOUSE_ID using the alias name CollectionWarehouseId.
     * @param value
     */
    public void setCollectionWarehouseId(Number value) {
        setAttributeInternal(COLLECTIONWAREHOUSEID, value);
    }

    /**Gets the attribute value for GIFTWRAP_FLAG using the alias name GiftwrapFlag.
     * @return
     */
    public String getGiftwrapFlag() {
        return (String) getAttributeInternal(GIFTWRAPFLAG);
    }

    /**Sets <code>value</code> as attribute value for GIFTWRAP_FLAG using the alias name GiftwrapFlag.
     * @param value
     */
    public void setGiftwrapFlag(String value) {
        setAttributeInternal(GIFTWRAPFLAG, value);
    }

    /**Gets the attribute value for GIFTWRAP_MESSAGE using the alias name GiftwrapMessage.
     * @return
     */
    public String getGiftwrapMessage() {
        return (String) getAttributeInternal(GIFTWRAPMESSAGE);
    }

    /**Sets <code>value</code> as attribute value for GIFTWRAP_MESSAGE using the alias name GiftwrapMessage.
     * @param value
     */
    public void setGiftwrapMessage(String value) {
        setAttributeInternal(GIFTWRAPMESSAGE, value);
    }

    /**Gets the attribute value for CALCULATED_ORDER_TOTAL using the alias name CalculatedOrderTotal.
     * @return
     */
    public Double getCalculatedOrderTotal() {
        return (Double) getAttributeInternal(CALCULATEDORDERTOTAL);
    }

    /**Sets <code>value</code> as attribute value for CALCULATED_ORDER_TOTAL using the alias name CalculatedOrderTotal.
     * @param value
     */
    public void setCalculatedOrderTotal(Double value) {
        setAttributeInternal(CALCULATEDORDERTOTAL, value);
    }

    /**Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @return
     */
    public Number getObjectVersionId() {
        return (Number) getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     * @param value value to set the OBJECT_VERSION_ID
     */
    public void setObjectVersionId(Number value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**Gets the attribute value for the calculated attribute TotalShippingCost.
     * @return
     */
    public Double getTotalShippingCost() {
        return (Double) getAttributeInternal(TOTALSHIPPINGCOST);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalShippingCost.
     * @param value
     */
    public void setTotalShippingCost(Double value) {
        setAttributeInternal(TOTALSHIPPINGCOST, value);
    }

    /**Gets the attribute value for DISCOUNT_AMOUNT using the alias name DiscountAmount.
     * @return
     */
    public Double getDiscountAmount() {
        return (Double) getAttributeInternal(DISCOUNTAMOUNT);
    }

    /**Sets <code>value</code> as attribute value for DISCOUNT_AMOUNT using the alias name DiscountAmount.
     * @param value
     */
    public void setDiscountAmount(Double value) {
        setAttributeInternal(DISCOUNTAMOUNT, value);
    }

    /**Gets the attribute value for the calculated attribute InvoiceTotal.
     * @return
     */
    public Double getInvoiceTotal() {
        return (Double) getAttributeInternal(INVOICETOTAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute InvoiceTotal.
     * @param value
     */
    public void setInvoiceTotal(Double value) {
        setAttributeInternal(INVOICETOTAL, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for TYPED_COUPON_CODE using the alias name TypedCouponCode.
     * @return
     */
    public String getTypedCouponCode() {
        return (String) getAttributeInternal(TYPEDCOUPONCODE);
    }

    /**Sets <code>value</code> as attribute value for TYPED_COUPON_CODE using the alias name TypedCouponCode.
     * @param value
     */
    public void setTypedCouponCode(String value) {
        setAttributeInternal(TYPEDCOUPONCODE, value);
    }

    /**Gets the attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId1.
     * @return
     */
    public Number getShipToAddressId1() {
        return (Number) getAttributeInternal(SHIPTOADDRESSID1);
    }

    /**Sets <code>value</code> as attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId1.
     * @param value
     */
    public void setShipToAddressId1(Number value) {
        setAttributeInternal(SHIPTOADDRESSID1, value);
    }

    /**Gets the attribute value for the calculated attribute ViewAttr.
     * @return
     */
    public String getViewAttr() {
        return (String) getAttributeInternal(VIEWATTR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ViewAttr.
     * @param value
     */
    public void setViewAttr(String value) {
        setAttributeInternal(VIEWATTR, value);
    }


    /**Gets the view accessor <code>RowSet</code> ShippingOptions.
     * @return
     */
    public RowSet getShippingOptions() {
        return (RowSet)getAttributeInternal(SHIPPINGOPTIONS);
    }

    /**Gets the view accessor <code>RowSet</code> Addresses.
     * @return
     */
    public RowSet getAddresses() {
        return (RowSet)getAttributeInternal(ADDRESSES);
    }

    /**Gets the view accessor <code>RowSet</code> PaymentOptions.
     * @return
     */
    public RowSet getPaymentOptions() {
        return (RowSet)getAttributeInternal(PAYMENTOPTIONS);
    }

    /**Gets the view accessor <code>RowSet</code> AddressesAndUsagesVO.
     * @return
     */
    public RowSet getAddressesAndUsagesVO() {
        return (RowSet)getAttributeInternal(ADDRESSESANDUSAGESVO);
    }

    /**Gets the view accessor <code>RowSet</code> MembershipDiscountsVO.
     * @return
     */
    public RowSet getMembershipDiscountsVO() {
        return (RowSet)getAttributeInternal(MEMBERSHIPDISCOUNTSVO);
    }

    /**Gets the view accessor <code>RowSet</code> Coupons.
     * @return
     */
    public RowSet getCoupons() {
        return (RowSet)getAttributeInternal(COUPONS);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     * @param index
     * @param attrDef
     * @return
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     * @param index
     * @param value
     * @param attrDef
     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute isCancelable.
     * @return the isCancelable
     */
    public Boolean getisCancelable() {
        return (Boolean) getAttributeInternal(ISCANCELABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isCancelable.
     * @param value value to set the  isCancelable
     */
    public void setisCancelable(Boolean value) {
        setAttributeInternal(ISCANCELABLE, value);
    }

    /**
     * Gets the attribute value for IS_PUBLISHABLE_EVENT using the alias name isPublishableEvent.
     * @return the IS_PUBLISHABLE_EVENT
     */
    public Boolean getisPublishableEvent() {
        return (Boolean) getAttributeInternal(ISPUBLISHABLEEVENT);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_PUBLISHABLE_EVENT using the alias name isPublishableEvent.
     * @param value value to set the IS_PUBLISHABLE_EVENT
     */
    public void setisPublishableEvent(Boolean value) {
        setAttributeInternal(ISPUBLISHABLEEVENT, value);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link AddressesVO.
     * @return
     */
    public RowIterator getAddressesVO() {
        return (RowIterator)getAttributeInternal(ADDRESSESVO);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link OrderItemsVO.
     * @return
     */
    public RowIterator getOrderItemsVO() {
        return (RowIterator)getAttributeInternal(ORDERITEMSVO);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link PaymentOptionsVO.
     * @return
     */
    public RowIterator getPaymentOptionsVO() {
        return (RowIterator)getAttributeInternal(PAYMENTOPTIONSVO);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link ShippingOptionsVO.
     * @return
     */
    public RowIterator getShippingOptionsVO() {
        return (RowIterator)getAttributeInternal(SHIPPINGOPTIONSVO);
    }
}
