package devguide.examples.appmodules.client;

import devguide.examples.appmodules.common.StoreFrontService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 30 11:21:10 MDT 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StoreFrontServiceClient extends ApplicationModuleImpl implements StoreFrontService {
    /**
     * This is the default constructor (do not remove).
     */
    public StoreFrontServiceClient() {
    }

    public String findOrderTotal(long orderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"findOrderTotal",new String [] {"long"},new Object[] {new Long(orderId)});
        return (String)_ret;
    }

    public String findOrderCustomer(long orderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"findOrderCustomer",new String [] {"long"},new Object[] {new Long(orderId)});
        return (String)_ret;
    }

    public void updateOrderStatus(long orderId, String newStatus) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateOrderStatus",new String [] {"long","java.lang.String"},new Object[] {new Long(orderId), newStatus});
        return;
    }

    public long createProduct(String name, String status, String shipCode) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createProduct",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {name, status, shipCode});
        return ((Long)_ret).longValue();
    }
}
