package conditionaldelete;

import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 28 15:48:38 MDT 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AddressesImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        AddressId {
            public Object get(AddressesImpl obj) {
                return obj.getAddressId();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setAddressId((Number)value);
            }
        }
        ,
        Address1 {
            public Object get(AddressesImpl obj) {
                return obj.getAddress1();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setAddress1((String)value);
            }
        }
        ,
        Address2 {
            public Object get(AddressesImpl obj) {
                return obj.getAddress2();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setAddress2((String)value);
            }
        }
        ,
        City {
            public Object get(AddressesImpl obj) {
                return obj.getCity();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setCity((String)value);
            }
        }
        ,
        PostalCode {
            public Object get(AddressesImpl obj) {
                return obj.getPostalCode();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setPostalCode((String)value);
            }
        }
        ,
        StateProvince {
            public Object get(AddressesImpl obj) {
                return obj.getStateProvince();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setStateProvince((String)value);
            }
        }
        ,
        CountryId {
            public Object get(AddressesImpl obj) {
                return obj.getCountryId();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setCountryId((String)value);
            }
        }
        ,
        Longitude {
            public Object get(AddressesImpl obj) {
                return obj.getLongitude();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setLongitude((Number)value);
            }
        }
        ,
        Latitude {
            public Object get(AddressesImpl obj) {
                return obj.getLatitude();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setLatitude((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(AddressesImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(AddressesImpl obj) {
                return obj.getCreationDate();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(AddressesImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(AddressesImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ObjectVersionId {
            public Object get(AddressesImpl obj) {
                return obj.getObjectVersionId();
            }

            public void put(AddressesImpl obj, Object value) {
                obj.setObjectVersionId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(AddressesImpl object);

        public abstract void put(AddressesImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ADDRESSID = AttributesEnum.AddressId.index();
    public static final int ADDRESS1 = AttributesEnum.Address1.index();
    public static final int ADDRESS2 = AttributesEnum.Address2.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int POSTALCODE = AttributesEnum.PostalCode.index();
    public static final int STATEPROVINCE = AttributesEnum.StateProvince.index();
    public static final int COUNTRYID = AttributesEnum.CountryId.index();
    public static final int LONGITUDE = AttributesEnum.Longitude.index();
    public static final int LATITUDE = AttributesEnum.Latitude.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int OBJECTVERSIONID = AttributesEnum.ObjectVersionId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AddressesImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("conditionaldelete.Addresses");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for AddressId, using the alias name AddressId.
     * @return the AddressId
     */
    public Number getAddressId() {
        return (Number)getAttributeInternal(ADDRESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressId.
     * @param value value to set the AddressId
     */
    public void setAddressId(Number value) {
        setAttributeInternal(ADDRESSID, value);
    }

    /**
     * Gets the attribute value for Address1, using the alias name Address1.
     * @return the Address1
     */
    public String getAddress1() {
        return (String)getAttributeInternal(ADDRESS1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Address1.
     * @param value value to set the Address1
     */
    public void setAddress1(String value) {
        setAttributeInternal(ADDRESS1, value);
    }

    /**
     * Gets the attribute value for Address2, using the alias name Address2.
     * @return the Address2
     */
    public String getAddress2() {
        return (String)getAttributeInternal(ADDRESS2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Address2.
     * @param value value to set the Address2
     */
    public void setAddress2(String value) {
        setAttributeInternal(ADDRESS2, value);
    }

    /**
     * Gets the attribute value for City, using the alias name City.
     * @return the City
     */
    public String getCity() {
        return (String)getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for City.
     * @param value value to set the City
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for PostalCode, using the alias name PostalCode.
     * @return the PostalCode
     */
    public String getPostalCode() {
        return (String)getAttributeInternal(POSTALCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostalCode.
     * @param value value to set the PostalCode
     */
    public void setPostalCode(String value) {
        setAttributeInternal(POSTALCODE, value);
    }

    /**
     * Gets the attribute value for StateProvince, using the alias name StateProvince.
     * @return the StateProvince
     */
    public String getStateProvince() {
        return (String)getAttributeInternal(STATEPROVINCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StateProvince.
     * @param value value to set the StateProvince
     */
    public void setStateProvince(String value) {
        setAttributeInternal(STATEPROVINCE, value);
    }

    /**
     * Gets the attribute value for CountryId, using the alias name CountryId.
     * @return the CountryId
     */
    public String getCountryId() {
        return (String)getAttributeInternal(COUNTRYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountryId.
     * @param value value to set the CountryId
     */
    public void setCountryId(String value) {
        setAttributeInternal(COUNTRYID, value);
    }

    /**
     * Gets the attribute value for Longitude, using the alias name Longitude.
     * @return the Longitude
     */
    public Number getLongitude() {
        return (Number)getAttributeInternal(LONGITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Longitude.
     * @param value value to set the Longitude
     */
    public void setLongitude(Number value) {
        setAttributeInternal(LONGITUDE, value);
    }

    /**
     * Gets the attribute value for Latitude, using the alias name Latitude.
     * @return the Latitude
     */
    public Number getLatitude() {
        return (Number)getAttributeInternal(LATITUDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Latitude.
     * @param value value to set the Latitude
     */
    public void setLatitude(Number value) {
        setAttributeInternal(LATITUDE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ObjectVersionId, using the alias name ObjectVersionId.
     * @return the ObjectVersionId
     */
    public Number getObjectVersionId() {
        return (Number)getAttributeInternal(OBJECTVERSIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObjectVersionId.
     * @param value value to set the ObjectVersionId
     */
    public void setObjectVersionId(Number value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param addressId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number addressId) {
        return new Key(new Object[]{addressId});
    }

    private boolean isDeleteAllowed() {
        byte s = this.getEntityState();
      return s==STATUS_NEW;
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
      if (isDeleteAllowed())
        super.remove();
      else
          throw new JboException("Delete not allowed in this view");
    }
}
