package devguide.advanced.inheritance.queries.client;

import devguide.advanced.inheritance.queries.common.PersonList;
import devguide.advanced.inheritance.queries.common.PersonListRow;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonListClient extends ViewUsageImpl implements PersonList {
    /**This is the default constructor (do not remove).
     */
    public PersonListClient() {
    }

    public PersonListRow createStaffRow() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"createStaffRow",null,null);
        return (PersonListRow)_ret;
    }

    public PersonListRow createSupplierRow() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"createSupplierRow",null,null);
        return (PersonListRow)_ret;
    }
}
