package devguide.advanced.inheritance.queries.client;

import devguide.advanced.inheritance.queries.common.StaffListRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaffListRowClient extends PersonListRowClient implements StaffListRow {
    /**This is the default constructor (do not remove).
     */
    public StaffListRowClient() {
    }


    public void performStaffFunction() {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"performStaffFunction",null,null);
        return;
    }

    public String getDiscountEligible() {
        return (String)getAttribute("DiscountEligible");
    }

    public void setDiscountEligible(String value) {
        setAttribute("DiscountEligible", value);
    }
}
