package devguide.advanced.inheritance.queries.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface PersonList extends ViewObject {
    PersonListRow createStaffRow();

    PersonListRow createSupplierRow();
}
