package devguide.advanced.inheritance.queries.common;

import devguide.advanced.inheritance.PersonsImpl;


import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonListRowImpl extends ViewRowImpl implements PersonListRow {
    public static final int PERSONID = 0;
    public static final int PRINCIPALNAME = 1;
    public static final int TITLE = 2;
    public static final int FIRSTNAME = 3;
    public static final int LASTNAME = 4;
    public static final int PERSONTYPECODE = 5;
    public static final int SUPPLIERID = 6;
    public static final int PROVISIONEDFLAG = 7;
    public static final int PRIMARYADDRESSID = 8;
    public static final int REGISTEREDDATE = 9;
    public static final int MEMBERSHIPID = 10;
    public static final int EMAIL = 11;
    public static final int CONFIRMEDEMAIL = 12;
    public static final int PHONENUMBER = 13;
    public static final int MOBILEPHONENUMBER = 14;
    public static final int CREDITLIMIT = 15;
    public static final int DATEOFBIRTH = 16;
    public static final int MARITALSTATUSCODE = 17;
    public static final int GENDER = 18;
    public static final int CHILDRENUNDER18 = 19;
    public static final int APPROXIMATEINCOME = 20;
    public static final int CONTACTMETHODCODE = 21;
    public static final int CONTACTABLEFLAG = 22;
    public static final int CONTACTBYAFFILLIATESFLAG = 23;
    public static final int CREATEDBY = 24;
    public static final int CREATIONDATE = 25;
    public static final int LASTUPDATEDBY = 26;
    public static final int LASTUPDATEDATE = 27;
    public static final int OBJECTVERSIONID = 28;

    public void performPersonFunction() {
    getThePerson().performPersonFunction();;
    }

    /**This is the default constructor (do not remove).
     */
    public PersonListRowImpl() {
    }

    /**Gets ThePerson entity object.
     */
    public PersonsImpl getThePerson() {
        return (PersonsImpl)getEntity(0);
    }

    /**Gets the attribute value for PERSON_ID using the alias name PersonId.
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for PRINCIPAL_NAME using the alias name PrincipalName.
     */
    public String getPrincipalName() {
        return (String) getAttributeInternal(PRINCIPALNAME);
    }

    /**Sets <code>value</code> as attribute value for PRINCIPAL_NAME using the alias name PrincipalName.
     */
    public void setPrincipalName(String value) {
        setAttributeInternal(PRINCIPALNAME, value);
    }

    /**Gets the attribute value for TITLE using the alias name Title.
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**Gets the attribute value for FIRST_NAME using the alias name FirstName.
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for LAST_NAME using the alias name LastName.
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for PERSON_TYPE_CODE using the alias name PersonTypeCode.
     */
    public String getPersonTypeCode() {
        return (String) getAttributeInternal(PERSONTYPECODE);
    }

    /**Sets <code>value</code> as attribute value for PERSON_TYPE_CODE using the alias name PersonTypeCode.
     */
    public void setPersonTypeCode(String value) {
        setAttributeInternal(PERSONTYPECODE, value);
    }

    /**Gets the attribute value for SUPPLIER_ID using the alias name SupplierId.
     */
    public Number getSupplierId() {
        return (Number) getAttributeInternal(SUPPLIERID);
    }

    /**Sets <code>value</code> as attribute value for SUPPLIER_ID using the alias name SupplierId.
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**Gets the attribute value for PROVISIONED_FLAG using the alias name ProvisionedFlag.
     */
    public String getProvisionedFlag() {
        return (String) getAttributeInternal(PROVISIONEDFLAG);
    }

    /**Sets <code>value</code> as attribute value for PROVISIONED_FLAG using the alias name ProvisionedFlag.
     */
    public void setProvisionedFlag(String value) {
        setAttributeInternal(PROVISIONEDFLAG, value);
    }

    /**Gets the attribute value for PRIMARY_ADDRESS_ID using the alias name PrimaryAddressId.
     */
    public Number getPrimaryAddressId() {
        return (Number) getAttributeInternal(PRIMARYADDRESSID);
    }

    /**Sets <code>value</code> as attribute value for PRIMARY_ADDRESS_ID using the alias name PrimaryAddressId.
     */
    public void setPrimaryAddressId(Number value) {
        setAttributeInternal(PRIMARYADDRESSID, value);
    }

    /**Gets the attribute value for REGISTERED_DATE using the alias name RegisteredDate.
     */
    public Date getRegisteredDate() {
        return (Date) getAttributeInternal(REGISTEREDDATE);
    }

    /**Sets <code>value</code> as attribute value for REGISTERED_DATE using the alias name RegisteredDate.
     */
    public void setRegisteredDate(Date value) {
        setAttributeInternal(REGISTEREDDATE, value);
    }

    /**Gets the attribute value for MEMBERSHIP_ID using the alias name MembershipId.
     */
    public Number getMembershipId() {
        return (Number) getAttributeInternal(MEMBERSHIPID);
    }

    /**Sets <code>value</code> as attribute value for MEMBERSHIP_ID using the alias name MembershipId.
     */
    public void setMembershipId(Number value) {
        setAttributeInternal(MEMBERSHIPID, value);
    }

    /**Gets the attribute value for EMAIL using the alias name Email.
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**Gets the attribute value for CONFIRMED_EMAIL using the alias name ConfirmedEmail.
     */
    public String getConfirmedEmail() {
        return (String) getAttributeInternal(CONFIRMEDEMAIL);
    }

    /**Sets <code>value</code> as attribute value for CONFIRMED_EMAIL using the alias name ConfirmedEmail.
     */
    public void setConfirmedEmail(String value) {
        setAttributeInternal(CONFIRMEDEMAIL, value);
    }

    /**Gets the attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     */
    public String getPhoneNumber() {
        return (String) getAttributeInternal(PHONENUMBER);
    }

    /**Sets <code>value</code> as attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     */
    public void setPhoneNumber(String value) {
        setAttributeInternal(PHONENUMBER, value);
    }

    /**Gets the attribute value for MOBILE_PHONE_NUMBER using the alias name MobilePhoneNumber.
     */
    public String getMobilePhoneNumber() {
        return (String) getAttributeInternal(MOBILEPHONENUMBER);
    }

    /**Sets <code>value</code> as attribute value for MOBILE_PHONE_NUMBER using the alias name MobilePhoneNumber.
     */
    public void setMobilePhoneNumber(String value) {
        setAttributeInternal(MOBILEPHONENUMBER, value);
    }

    /**Gets the attribute value for CREDIT_LIMIT using the alias name CreditLimit.
     */
    public Number getCreditLimit() {
        return (Number) getAttributeInternal(CREDITLIMIT);
    }

    /**Sets <code>value</code> as attribute value for CREDIT_LIMIT using the alias name CreditLimit.
     */
    public void setCreditLimit(Number value) {
        setAttributeInternal(CREDITLIMIT, value);
    }

    /**Gets the attribute value for DATE_OF_BIRTH using the alias name DateOfBirth.
     */
    public Date getDateOfBirth() {
        return (Date) getAttributeInternal(DATEOFBIRTH);
    }

    /**Sets <code>value</code> as attribute value for DATE_OF_BIRTH using the alias name DateOfBirth.
     */
    public void setDateOfBirth(Date value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**Gets the attribute value for MARITAL_STATUS_CODE using the alias name MaritalStatusCode.
     */
    public String getMaritalStatusCode() {
        return (String) getAttributeInternal(MARITALSTATUSCODE);
    }

    /**Sets <code>value</code> as attribute value for MARITAL_STATUS_CODE using the alias name MaritalStatusCode.
     */
    public void setMaritalStatusCode(String value) {
        setAttributeInternal(MARITALSTATUSCODE, value);
    }

    /**Gets the attribute value for GENDER using the alias name Gender.
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**Sets <code>value</code> as attribute value for GENDER using the alias name Gender.
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**Gets the attribute value for CHILDREN_UNDER_18 using the alias name ChildrenUnder18.
     */
    public Number getChildrenUnder18() {
        return (Number) getAttributeInternal(CHILDRENUNDER18);
    }

    /**Sets <code>value</code> as attribute value for CHILDREN_UNDER_18 using the alias name ChildrenUnder18.
     */
    public void setChildrenUnder18(Number value) {
        setAttributeInternal(CHILDRENUNDER18, value);
    }

    /**Gets the attribute value for APPROXIMATE_INCOME using the alias name ApproximateIncome.
     */
    public Number getApproximateIncome() {
        return (Number) getAttributeInternal(APPROXIMATEINCOME);
    }

    /**Sets <code>value</code> as attribute value for APPROXIMATE_INCOME using the alias name ApproximateIncome.
     */
    public void setApproximateIncome(Number value) {
        setAttributeInternal(APPROXIMATEINCOME, value);
    }

    /**Gets the attribute value for CONTACT_METHOD_CODE using the alias name ContactMethodCode.
     */
    public String getContactMethodCode() {
        return (String) getAttributeInternal(CONTACTMETHODCODE);
    }

    /**Sets <code>value</code> as attribute value for CONTACT_METHOD_CODE using the alias name ContactMethodCode.
     */
    public void setContactMethodCode(String value) {
        setAttributeInternal(CONTACTMETHODCODE, value);
    }

    /**Gets the attribute value for CONTACTABLE_FLAG using the alias name ContactableFlag.
     */
    public String getContactableFlag() {
        return (String) getAttributeInternal(CONTACTABLEFLAG);
    }

    /**Sets <code>value</code> as attribute value for CONTACTABLE_FLAG using the alias name ContactableFlag.
     */
    public void setContactableFlag(String value) {
        setAttributeInternal(CONTACTABLEFLAG, value);
    }

    /**Gets the attribute value for CONTACT_BY_AFFILLIATES_FLAG using the alias name ContactByAffilliatesFlag.
     */
    public String getContactByAffilliatesFlag() {
        return (String) getAttributeInternal(CONTACTBYAFFILLIATESFLAG);
    }

    /**Sets <code>value</code> as attribute value for CONTACT_BY_AFFILLIATES_FLAG using the alias name ContactByAffilliatesFlag.
     */
    public void setContactByAffilliatesFlag(String value) {
        setAttributeInternal(CONTACTBYAFFILLIATESFLAG, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     */
    public Number getObjectVersionId() {
        return (Number) getAttributeInternal(OBJECTVERSIONID);
    }

    /**Sets <code>value</code> as attribute value for OBJECT_VERSION_ID using the alias name ObjectVersionId.
     */
    public void setObjectVersionId(Number value) {
        setAttributeInternal(OBJECTVERSIONID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            return getPersonId();
        case PRINCIPALNAME:
            return getPrincipalName();
        case TITLE:
            return getTitle();
        case FIRSTNAME:
            return getFirstName();
        case LASTNAME:
            return getLastName();
        case PERSONTYPECODE:
            return getPersonTypeCode();
        case SUPPLIERID:
            return getSupplierId();
        case PROVISIONEDFLAG:
            return getProvisionedFlag();
        case PRIMARYADDRESSID:
            return getPrimaryAddressId();
        case REGISTEREDDATE:
            return getRegisteredDate();
        case MEMBERSHIPID:
            return getMembershipId();
        case EMAIL:
            return getEmail();
        case CONFIRMEDEMAIL:
            return getConfirmedEmail();
        case PHONENUMBER:
            return getPhoneNumber();
        case MOBILEPHONENUMBER:
            return getMobilePhoneNumber();
        case CREDITLIMIT:
            return getCreditLimit();
        case DATEOFBIRTH:
            return getDateOfBirth();
        case MARITALSTATUSCODE:
            return getMaritalStatusCode();
        case GENDER:
            return getGender();
        case CHILDRENUNDER18:
            return getChildrenUnder18();
        case APPROXIMATEINCOME:
            return getApproximateIncome();
        case CONTACTMETHODCODE:
            return getContactMethodCode();
        case CONTACTABLEFLAG:
            return getContactableFlag();
        case CONTACTBYAFFILLIATESFLAG:
            return getContactByAffilliatesFlag();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case OBJECTVERSIONID:
            return getObjectVersionId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            setPersonId((Number)value);
            return;
        case PRINCIPALNAME:
            setPrincipalName((String)value);
            return;
        case TITLE:
            setTitle((String)value);
            return;
        case FIRSTNAME:
            setFirstName((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case PERSONTYPECODE:
            setPersonTypeCode((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case PROVISIONEDFLAG:
            setProvisionedFlag((String)value);
            return;
        case PRIMARYADDRESSID:
            setPrimaryAddressId((Number)value);
            return;
        case REGISTEREDDATE:
            setRegisteredDate((Date)value);
            return;
        case MEMBERSHIPID:
            setMembershipId((Number)value);
            return;
        case EMAIL:
            setEmail((String)value);
            return;
        case CONFIRMEDEMAIL:
            setConfirmedEmail((String)value);
            return;
        case PHONENUMBER:
            setPhoneNumber((String)value);
            return;
        case MOBILEPHONENUMBER:
            setMobilePhoneNumber((String)value);
            return;
        case CREDITLIMIT:
            setCreditLimit((Number)value);
            return;
        case DATEOFBIRTH:
            setDateOfBirth((Date)value);
            return;
        case MARITALSTATUSCODE:
            setMaritalStatusCode((String)value);
            return;
        case GENDER:
            setGender((String)value);
            return;
        case CHILDRENUNDER18:
            setChildrenUnder18((Number)value);
            return;
        case APPROXIMATEINCOME:
            setApproximateIncome((Number)value);
            return;
        case CONTACTMETHODCODE:
            setContactMethodCode((String)value);
            return;
        case CONTACTABLEFLAG:
            setContactableFlag((String)value);
            return;
        case CONTACTBYAFFILLIATESFLAG:
            setContactByAffilliatesFlag((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case OBJECTVERSIONID:
            setObjectVersionId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
