package devguide.advanced.inheritance.queries.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface PersonListRow extends Row {
    void performPersonFunction();

    String getEmail();

    String getFirstName();

    String getLastName();

    String getGender();

    Number getPersonId();

    String getPersonTypeCode();

    String getPhoneNumber();

    Number getSupplierId();

    void setEmail(String value);

    void setFirstName(String value);

    void setGender(String value);

    void setLastName(String value);

    void setPersonId(Number value);

    void setPersonTypeCode(String value);

    void setPhoneNumber(String value);
}
