package devguide.advanced.inheritance.queries.common;

import devguide.advanced.inheritance.queries.common.PersonList;
import devguide.advanced.inheritance.queries.common.PersonListRow;

import oracle.jbo.NameValuePairs;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonListImpl extends ViewObjectImpl implements PersonList {
    /**This is the default constructor (do not remove).
     */
    public PersonListImpl() {
    }
    
    public PersonListRow createStaffRow() {
    NameValuePairs nvp = new NameValuePairs();
    nvp.setAttribute("PersonTypeCode","STAFF");
    return (PersonListRow)createAndInitRow(nvp);
    }
    public PersonListRow createSupplierRow() {
    NameValuePairs nvp = new NameValuePairs();
    nvp.setAttribute("PersonTypeCode","SUPP");
    return (PersonListRow)createAndInitRow(nvp);
    }
}
