package devguide.advanced.inheritance.queries.common;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface StaffListRow extends PersonListRow {
    void performStaffFunction();

    String getDiscountEligible();

    void setDiscountEligible(String value);
}
