package oracle.fodemo.storefront.store.queries.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 08 16:20:17 MST 2009
// ---------------------------------------------------------------------
public interface PersonsVO extends ViewObject {
    String getuserPrincipal();

    String findPerson(String principalName);
}
