package devguide.advanced.baseproject.extsub.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ProductsRow extends Row {
    void setProductName(String value);

    void setProductId(Number value);

    String getProductName();

    Number getProductId();
}
