package devguide.advanced.customprops.client;

import devguide.advanced.customprops.common.ProductModule;

import devguide.advanced.customprops.common.Products;

import java.io.Serializable;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductModuleClient extends ApplicationModuleImpl implements ProductModule {
    /**This is the default constructor (do not remove).
     */
    public ProductModuleClient() {
    }

    public void setAppModuleCustomProperty(String name, Serializable value) {
        Object _ret = 
            this.riInvokeExportedMethod(this,"setAppModuleCustomProperty",new String [] {"java.lang.String","java.io.Serializable"},new Object[] {name, value});
        return;
    }

    public Products useProducts() {
        Object _ret = this.riInvokeExportedMethod(this,"useProducts",null,null);
        return (Products)_ret;
    }
}
